#pragma config(Sensor, in1,    controlSwitch,  sensorAnalog)
#pragma config(Motor,  port4,           FLmotor,       tmotorVex393, openLoop)
#pragma config(Motor,  port5,           BLmotor,       tmotorVex393, openLoop)
#pragma config(Motor,  port6,           BRmotor,       tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port7,           FRmotor,       tmotorVex393, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(15)
#pragma userControlDuration(125)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

//Important Functions

void Drive(int S, int T) //S for speed T for time
{
	motor[FLmotor] = S;
	motor[BLmotor] = S;
	motor[BRmotor] = S;
	motor[FRmotor] = S;
	wait1Msec(T);
}


/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
  // Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
  Drive(127,1500);
  Drive(-127,1500);
  Drive(0,6000);
  Drive(127,1500);
  Drive(-127,1500);
  Drive(0,3000);
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{

	while (SensorValue(controlSwitch) == 0) // no switch for tank controls
	{
	 motor[BLmotor] = vexRT[Ch3];
	 motor[FLmotor] = vexRT[Ch3];
	 motor[BRmotor] = vexRT[Ch2];
	 motor[FRmotor] = vexRT[Ch2];
  }

  while (SensorValue(controlSwitch) == 1) // have switch in analog port 1 for steve controls
  {
  	wait1Msec(1);
		if (abs(vexRT[Ch4]) > abs(vexRT[Ch3]))
		{
			motor[BRmotor] = -(vexRT[Ch4]);
			motor[FRmotor] = -(vexRT[Ch4]);
			motor[BLmotor] = vexRT[Ch4];
			motor[FLmotor] = vexRT[Ch4];
		}
		else if (abs(vexRT[Ch3]) >= abs(vexRT[Ch4]))
		{
			motor[BRmotor] = vexRT[Ch3];
			motor[FRmotor] = vexRT[Ch3];
			motor[BLmotor] = vexRT[Ch3];
			motor[FLmotor] = vexRT[Ch3];
		}
	}

	//while(vexRT[Ch4] == -127) || vexRT[Ch1] == -127)
	//{
	// motor[BRmotor] = 127;
	// motor[FRmotor] = 127;
	// motor[BLmotor] = -127;
	// motor[FLmotor] = -127;
	//}

	//while(vexRT[Ch4] == 127) || vexRT[Ch1] == 127)
	//{
	// motor[BRmotor] = -127;
	// motor[FRmotor] = -127;
	// motor[BLmotor] = 127;
	// motor[FLmotor] = 127;
	//}


	//while(1 == 1)
	//{
	// motor[BLmotor] = vexRT[Ch3];
	// motor[BLmotor] = vexRT[Ch2];
	// motor[BRmotor] = vexRT[Ch3];
	// motor[BRmotor] = vexRT[Ch2];
	// motor[FRmotor] = vexRT[Ch3];
	// motor[FRmotor] = vexRT[Ch2];
	// motor[FLmotor] = vexRT[Ch3];
	// motor[FLmotor] = vexRT[Ch2];
	//}
}
