#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    controlSwitch,  sensorAnalog)
#pragma config(Sensor, in2,    RedOrBluSwitch, sensorAnalog)
#pragma config(Sensor, in3,    LeftOrRightSwitch, sensorAnalog)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port1,           FlapperL,      tmotorVex269, openLoop)
#pragma config(Motor,  port2,           ArmMotorR2,    tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port3,           ArmMotorR,     tmotorVex393, openLoop)
#pragma config(Motor,  port4,           FLmotor,       tmotorVex393, openLoop)
#pragma config(Motor,  port5,           BLmotor,       tmotorVex393, openLoop, encoder, encoderPort, I2C_1, 1000)
#pragma config(Motor,  port6,           BRmotor,       tmotorVex393, openLoop, reversed, encoder, encoderPort, I2C_2, 1000)
#pragma config(Motor,  port7,           FRmotor,       tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port8,           ArmMotorL,     tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port9,           ArmMotorL2,    tmotorVex393, openLoop)
#pragma config(Motor,  port10,          FlapperR,      tmotorVex269, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(15)
#pragma userControlDuration(125)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

//Important Functions

void Drive(int motorspeed, int armspeed, int time) // meant for autonomous; motors drive at motorspeed, arms drive at armspeed, time is how long it takes
{
	motor[FLmotor] = motorspeed;
	motor[BLmotor] = motorspeed;
	motor[BRmotor] = motorspeed;
	motor[FRmotor] = motorspeed;
	motor[ArmMotorL] = armspeed;
	motor[ArmMotorR] = armspeed;
	motor[ArmMotorL2] = armspeed;
	motor[ArmMotorR2] = armspeed;
	wait1Msec(time);
}

void Turn(int motorspeed, int time) // meant for autonomous; motors turn at motorspeed, time is how long it takes
{
	motor[FLmotor] = motorspeed;
	motor[BLmotor] = motorspeed;
	motor[BRmotor] = -(motorspeed);
	motor[FRmotor] = -(motorspeed);
	wait1Msec(time);
}

void FlapperSpin() // meant for control of the flapper blades on the arms
{
	if (vexRT[Btn5D] == 1) //if 5D is pressed
  {
		motor[FlapperL] = 127; //flappers move inward
		motor[FlapperR] = 127;
	}
	else if (vexRT[Btn6D] == 1) //else if 6D is pressed
	{
		motor[FlapperL] = -127; //flappers move inward
		motor[FlapperR] = -127;
  }
  else //if nothing happens
	{
		motor[FlapperL] = 0; //nothing happens
		motor[FlapperR] = 0;
	}
}

void AutoPlaceholder1() //red side autonomous
{
	SensorValue(I2C_1) = 0; //reset sensor
	SensorValue(I2C_2) = 0;
  Drive(127,127,1500); //go forward, move arm (SCORE FIRST BIG BALL)
  Drive(-127,0,1000); //go back
  Drive(0,-127,200); //move arm down
  Drive(0,25,1000); //fix arm
  Turn(127,585); //turn right
  Drive(127,0,1500); //go forward
  Turn(-127,585); //turn left
  Drive(127,127,1100); //go forward, move arm (SCORE SECOND BIG BALL)
  Drive(-127,0,1000); //go back
  Drive(0,-127,200); //move arm down
}

void AutoPlaceholder2() //blue side autonomous
{
	SensorValue(I2C_1) = 0; //reset sensor
	SensorValue(I2C_2) = 0;
  Drive(127,127,1500); //go forward, move arm (SCORE FIRST BIG BALL)
  Drive(-127,0,1000); //go back
  Drive(0,-127,200); //move arm down
  Drive(0,25,1000); //fix arm
  Turn(-127,585); //turn left
  Drive(127,0,1500); //go forward
  Turn(127,585); //turn right
  Drive(127,127,1100); //go forward, move arm (SCORE SECOND BIG BALL)
  Drive(-127,0,1000); //go back
  Drive(0,-127,200); //move arm down
}

void AutoPlaceholder3() // IN CASE OF EMERGENCY (the autonomous doesnt work)
{
	SensorValue(I2C_1) = 0; //reset sensor
	SensorValue(I2C_2) = 0;
  Drive(127,127,1500);
  Drive(-127,0,1500);
  Drive(0,-127,1500);
  //Turn(127,750);
  Drive(0,0,4500); // TURN IT HERE
  Drive(127,127,2000);
  Drive(-127,0,2000);
  Drive(0,-127,2000);
}

float FixedI2C_2; // TO BE USED IN A FUTURE VERSION

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
  // Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

// Autonomous uses jumper switchs put in by the team to determine where it is on the field.
// It uses two switches to check whether its on the red side or blue side
// and as to whether is is in the middle zone or the descoring zone.
task autonomous()
{
	//if no switch in port 2 choose red
  if (SensorValue(RedOrBluSwitch) > 1)
  {
  	//if no switch in port 3 choose left
  	if (SensorValue(LeftOrRightSwitch) > 1)
  	{
  		AutoPlaceholder1(); //CODE FOR RED AND LEFT GOES HERE
  	}
  	//if switch in port 3 choose right
  	else if (SensorValue(LeftOrRightSwitch) == 0)
  	{
  		//AutoPlaceholder1(); //CODE FOR RED AND RIGHT GOES HERE; for now these requirements disable the autonomous
  	}
  }
  //if switch in port 2 choose blu
  else if (SensorValue(RedOrBluSwitch) == 0)
  {
  	//if no switch in port 3 choose left
  	if (SensorValue(LeftOrRightSwitch) > 1)
  	{
  		AutoPlaceholder2(); //CODE FOR BLU AND LEFT GOES HERE
  	}
  	//if switch in port 3 choose right
  	else if (SensorValue(LeftOrRightSwitch) == 0)
  	{
  		//AutoPlaceholder2(); //CODE FOR BLU AND RIGHT GOES HERE; for now these requirements disable the autonomous
  	}
  }
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

//No switch in port 1 for tank controls
//Switch in port 1 for WIP one joystick gaming-esque controls (mainly used for testing motors)
task usercontrol()
{
  SensorValue(I2C_1) = 0; //reset sensors
  SensorValue(I2C_2) = 0;
	while (1==1)
		{
		FixedI2C_2 = -(SensorValue(I2C_2)); // to fix sensor bug
		if (SensorValue(controlSwitch) > 1) //if theres no switch then tank controls
		{
		 while (1==1) // not sure if necessary
		 {
		 motor[BLmotor] = vexRT[Ch3]; //left is controlled by left joystick
		 motor[FLmotor] = vexRT[Ch3];
		 motor[BRmotor] = vexRT[Ch2]; //right is controlled by right joystick
		 motor[FRmotor] = vexRT[Ch2];
		 if (vexRT[Btn6U] == 1) //if 5U is pressed
		 {
		   motor[ArmMotorL] = 127; //arms move up
		   motor[ArmMotorR] = 127;
		   motor[ArmMotorL2] = 127;
		   motor[ArmMotorR2] = 127;
		 }
		 else if (vexRT[Btn5U] == 1) //else if 6U is pressed
		 {
		   motor[ArmMotorL] = -127; //arms move down
		   motor[ArmMotorR] = -127;
		   motor[ArmMotorL2] = -127;
		   motor[ArmMotorR2] = -127;
		 }
		 else // if nothing happens
		 {
		   motor[ArmMotorL] = 0; // nothing happens
		   motor[ArmMotorR] = 0; // meant to prevent arm motors from moving at wrong times
		   motor[ArmMotorL2] = 0;
		   motor[ArmMotorR2] = 0;
		 }
		 FlapperSpin(); // for movement of flapper motors
 	  }
    }
 	  else if (SensorValue(controlSwitch) == 0) //if theres a switch then one joystick controls
 		{
 			while (1==1) // for reference: LR = direction left joystick is in left or right, UD = direction left joystick is in up or down
 				{
		 	  if (abs(vexRT[Ch4]) > abs(vexRT[Ch3])) //if absolute value of LR > absolute value of UD
				{
				motor[BRmotor] = -(vexRT[Ch4]); //LR is the chosen control
				motor[FRmotor] = -(vexRT[Ch4]); //right side is inverted speed of LR
				motor[BLmotor] = vexRT[Ch4]; //left side isnt inverted
				motor[FLmotor] = vexRT[Ch4]; //so that it turns in direction of LR
				}
				else if (abs(vexRT[Ch3]) >= abs(vexRT[Ch4])) //if absolute value of LR <= absolute value of UD
				{
				motor[BRmotor] = vexRT[Ch3]; //UD is the chosen control
				motor[FRmotor] = vexRT[Ch3]; //drive forwards/backwards at UD speed
				motor[BLmotor] = vexRT[Ch3];
				motor[FLmotor] = vexRT[Ch3];
				}
				motor[ArmMotorL] = vexRT[Ch2]; //arm motors move depending on how high/low the right joystick is
				motor[ArmMotorR] = vexRT[Ch2];
				motor[ArmMotorL2] = vexRT[Ch2];
				motor[ArmMotorR2] = vexRT[Ch2];
				FlapperSpin(); // meant for flapper motors to operate
			}
		}
	}
}
