#pragma config(Motor,  port2,           FLmotor,       tmotorVex269, openLoop)
#pragma config(Motor,  port3,           FRmotor,       tmotorVex269, openLoop, reversed)
#pragma config(Motor,  port4,           BLmotor,       tmotorVex269, openLoop)
#pragma config(Motor,  port5,           BRmotor,       tmotorVex269, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(15)
#pragma userControlDuration(145)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!
/* ROBOTICS CONTROL MANUAL FOR STEVE'S TEAM (name to be determined)
autonomous will move robot forward, back, pause, repeat
left joystick = left wheels
right joystick = right wheels
planning to simplify this soon */

void Drive(int S)
{
	motor[BLmotor]=S; //drive according to S (speed level)
	motor[BRmotor]=S;
	motor[FLmotor]=S;
	motor[FRmotor]=S;
}

void NDrive(int S)
{
	motor[BLmotor]=-S; //drive according to S (speed level)
	motor[BRmotor]=-S;
	motor[FLmotor]=-S;
	motor[FRmotor]=-S;
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
  // Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
  Drive(127);
  wait1Msec(1500);
  NDrive(127);
  wait1Msec(1500);
  Drive(0);
  wait1Msec(6000);
  Drive(127);
  wait1Msec(1500);
  NDrive(127);
  wait1Msec(1500);
  Drive(0);
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	while (true) //might want to change to 1==1 but i think this runs the same so
	{
	  //Right side of the robot is controlled by the right joystick, Y-axis
		motor[FRmotor] = vexRT[Ch2];
		motor[BRmotor]  = vexRT[Ch2];
		//Left side of the robot is controlled by the left joystick, Y-axis
		motor[FLmotor] = vexRT[Ch3];
		motor[BLmotor]  = vexRT[Ch3];
    //NOTE: in future make controls simpler and port to only one joystick?
	}
}
