#pragma config(Motor,  port1,           FL,            tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           BL,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           FR,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           BR,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           lift,          tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

//Coding Check Instructions

//Define a boolean variable named "isRoboticsFun" and set it to an appropriate value

//Define a string variable but do not set it to any value

//Define two variables a and b; both variables must be the same number but
//one must have a decimal place (a), the other must not (b)

//Create a function named "basicFunction" that requires an int value g. The function
//sets the value of g equal to the rounded up value of sin(|g|^2). Be careful to use
//the right math functions.

//Create a task named "basicTask". In basicTask, a for loop needs to run 10 times.
//The for loop each time needs to take the current loop value and set a to the square
//root of the loop value.

//In autonomous, delay for 5 seconds and then start the basicTask

//In user control, start the basicFunction but make sure the basicFunction only runs
//once at the start of the user control

//Define four wheel motors in motor and sensor setup

//In user control, set it so that the left motors are continually controlled by
//the left joystick up and down and the right motors are controlled by the right
//joystick up and down

//Define a lift motor in motor and sensor setup

//In user control, use logic statements so that button 5U moves the lift motor up,
//button 6U moves the lift motor down, and no buttons pressed will stop the motor

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

bool isRoboticsFun = true;
string name;
float a = 3.0;
int b = 3;

void basicFunction(int g) {
	g = ceil(sin(pow((fabs(g)),2)));
}

task basicTask() {
	for (int i = 1;i <= 10;i++) {
		a = sqrt(i);
	}
}

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
  // ..........................................................................
  // Insert user code here.
  // ..........................................................................

	wait1Msec(5000);
	startTask(basicTask);

  // Remove this function call once you have "real" code.
  AutonomousCodePlaceholderForTesting();
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
  // User control code here, inside the loop
	basicFunction(2);
  while (true)
  {
    motor[BL] = vexRT[Ch3];
    motor[FL] = vexRT[Ch3];
    motor[BR] = vexRT[Ch2];
    motor[FR] = vexRT[Ch2];

    if (vexRT[Btn5U] == 1) {
    	motor[lift] = 127;
  	} else if (vexRT[Btn6U] == 1) {
  		motor[lift] = -127;
  	} else {
  		motor[lift] = 0;
  	}
  }
}
