#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    betaTest,       sensorAnalog)
#pragma config(Sensor, I2C_1,  leftEncoder,    sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  rightEncoder,   sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port2,           FL,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           BL,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           FR,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           BR,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           LiftTL,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           LiftBL,        tmotorVex393_MC29, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port8,           LiftTR,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           LiftBR,        tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_2)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"
#include "SongTasks.c" //Songs to be used in the program

int testVar = 1;
//int lspeed;
//int rspeed;
int time = 0;
float speed = 0;
bool pFlag = false;
int debug = 0;
string line1;
string line2;

string color = "Red";
string side = "Left";
bool ready = false;
bool pressed = false;

//bool click = false;
//bool check = false;
//int seed = 0;
//int step = 1;
//int timeleft = 15000;
//int timechosen;

//void setRandomSeed() {
//	clearLCDLine(0);
//	clearLCDLine(1);
//	check = false;
//	click = false;
//	while (check == false) {
//		bLCDBacklight = true;									// Turn on LCD Backlight
//		displayLCDPos(0,0);
//		string display1;
//		sprintf(display1, "SET RANDSEED");
//		displayNextLCDString(display1);
//		displayLCDPos(1,0);
//		string display2;
//		sprintf(display2, "SEED: %4d", seed);
//		displayNextLCDString(display2);
//		if (nLCDButtons == 1 && click == false) {
//			click = true;
//			seed = seed - 1;
//		} else if (nLCDButtons == 4 && click == false) {
//			click = true;
//			seed = seed + 1;
//		} else if (nLCDButtons == 2) {
//			check = true;
//		} else if (nLCDButtons == 0 && click == true) {
//			click = false;
//		}
//	}
//	clearLCDLine(0);
//	clearLCDLine(1);
//	bLCDBacklight = true;									// Turn on LCD Backlight
//	displayLCDPos(0,0);
//	string display1;
//	sprintf(display1, "RANDSEED SET!");
//	displayNextLCDString(display1);
//	displayLCDPos(1,0);
//	string display2;
//	sprintf(display2, "SEED: %4d", seed);
//	displayNextLCDString(display2);
//}

//void dumbAutonomous() {
//	srand(seed);
//	timeleft = 15000;
//	startTask(smb3);
//	while (timeleft > 0) {
//		clearLCDLine(0);
//		clearLCDLine(1);
//		bLCDBacklight = true;									// Turn on LCD Backlight
//		displayLCDPos(0,0);
//		string display1;
//		sprintf(display1, "RANDAUTO");
//		displayNextLCDString(display1);
//		displayLCDPos(1,0);
//		string display2;
//		sprintf(display2, "STEP: %2d", step);
//		displayNextLCDString(display2);
//		lspeed = random(254) - 127;
//		rspeed = random(254) - 127;
//		motor[BL] = lspeed;
//		motor[FL] = lspeed;
//		motor[BR] = rspeed;
//		motor[FR] = rspeed;
//		timechosen = random(timeleft);
//		timeleft = timeleft - timechosen;
//		wait1Msec(timechosen);
//		step = step + 1;
//	}
//	motor[BL] = 0;
//	motor[FL] = 0;
//	motor[BR] = 0;
//	motor[FR] = 0;
//	clearLCDLine(0);
//	clearLCDLine(1);
//	bLCDBacklight = true;									// Turn on LCD Backlight
//	displayLCDPos(0,0);
//	string display1;
//	sprintf(display1, "RANDAUTO");
//	displayNextLCDString(display1);
//	displayLCDPos(1,0);
//	string display2;
//	sprintf(display2, "COMPLETE");
//	displayNextLCDString(display2);
//}

task timer() {
	time = 0;
	while (true) {
		wait1Msec(1);
		time = time + 1;
	}
}

void getSpeed() { //Returns degrees per second
	speed = ((nMotorEncoder[LiftBL])/time)*1000;  //Needs conversion
}

task preAutonData() {
	while (true) {
		bLCDBacklight = true;
	 	sprintf(line1, "Color: %4s", color);
	 	sprintf(line2, "Side: %5s", side);
	 	displayLCDPos(0, 0);
	  displayNextLCDString(line1);
	  displayLCDPos(1, 0);
	  displayNextLCDString(line2);
	}
}

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
  bStopTasksBetweenModes = true;
  if (SensorValue[betaTest] == 0) {
  	testVar = 0; //Enable beta features
  	//setRandomSeed();
    } else {
    testVar = 1; //Disable beta features
	}
	//Reset encoders
	nMotorEncoder[LiftBL] = 0;
	nMotorEncoder[LiftBR] = 0;
	startTask(preAutonData);
	startTask(timer);
	while (ready == false) {
		if (nLCDButtons == 1 && pressed == false) {
			pressed = true;
			if (color == "Red") {
				color = "Blue";
			}	else {
	      color = "Red";
			}
			clearLCDLine(0);
			clearLCDLine(1);
		}	else if (nLCDButtons == 2 && pressed == false) {
			pressed = true;
			if (side == "Left") {
				side = "Right";
			}	else {
	      side = "Left";
			}
			clearLCDLine(0);
			clearLCDLine(1);
		}	else if (nLCDButtons == 4 && pressed == false) {
			pressed = true;
			ready = true;
		}	else if (nLCDButtons == 0 && pressed == true) {
			pressed = false;
		}
	}
	stopTask(preAutonData);
	stopTask(timer);
	bLCDBacklight = true;
	clearLCDLine(0);
	clearLCDLine(1);
	if ((time % 10) <= 3) {
		sprintf(line1, "AUTO SET!");
		sprintf(line2, "READY");
	}	else if ((time % 10) <= 5) {
		sprintf(line1, "AUTO GET!");
		sprintf(line2, "REEFY");
	}	else if ((time % 10) <= 7) {
		sprintf(line1, "SET AUTO!");
		sprintf(line2, "GRAVY");
	}	else if ((time % 10) <= 8) {
		sprintf(line1, "SORRY BRO!");
		sprintf(line2, "- YOUNG");
	}	else if ((time % 10) <= 9) {
		sprintf(line1, "HEY, THAT'S");
		sprintf(line2, "PRETTY GOOD!");
	}
	displayLCDPos(0, 0);
	displayNextLCDString(line1);
	displayLCDPos(1, 0);
	displayNextLCDString(line2);
	wait1Msec(2000);
	clearLCDLine(0);
	clearLCDLine(1);
	playSound(soundBlip);
	playSound(soundException);
	playSound(soundBeepBeep);
	playSound(soundLowBuzz);
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
  // ..........................................................................
  // Insert user code here.
  // ..........................................................................

  // Remove this function call once you have "real" code.
	soundPlay = true;
  startTask(pacman);
	//if (testVar == 0) {
 // 	dumbAutonomous();
	//}

}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
	//Start tasks here
  soundPlay = true;
  startTask(pacman);
  while (true)
  {
  	debug = vexRT[Ch3];
		//Drive motor controls
		motor[BL] = vexRT[Ch3];
		motor[FL] = vexRT[Ch3];
		motor[BR] = vexRT[Ch2];
		motor[FR] = vexRT[Ch2];
		//Sound controls
		if (soundPlay == false) {
			if (vexRT[Btn7L] == 1) {
				soundPlay = true;
				startTask(zelda);
			} else if (vexRT[Btn7D] == 1) {
				soundPlay = true;
				startTask(ffvii);
			}	else if (vexRT[Btn7R] == 1) {
				soundPlay = true;
				startTask(smb3);
		  } else if (vexRT[Btn8L] == 1) {
  			soundPlay = true;
  			startTask(smbdeath);
  		} else if (vexRT[Btn8R] == 1) {
  			soundPlay = true;
  			startTask(smw2_map);
			}	else if (vexRT[Btn8D] == 1) {
				soundPlay = true;
				startTask(PPAP);
			}	else if (vexRT[Btn8U] == 1) {
		  	soundPlay = true;
		  	startTask(PokemonGO2);
			}
		}
		if (nVexRCReceiveState & vrXmit2) { //Enable partner controls
			motor[LiftTL] = vexRT[Ch3Xmtr2];
			motor[LiftBL] = vexRT[Ch3Xmtr2];
			motor[LiftTR] = vexRT[Ch3Xmtr2];
			motor[LiftBR] = vexRT[Ch3Xmtr2];
		}	else { //Single controls
			if (vexRT[Btn5U] == 1) {
				if (pFlag == false) {
					pFlag = true;
					nMotorEncoder[LiftBL] = 0;
					nMotorEncoder[LiftBR] = 0;
					startTask(timer);
				}
				motor[LiftTL] = 127;
				motor[LiftBL] = 127;
				motor[LiftTR] = 127;
				motor[LiftBR] = 127;
			}	else if (vexRT[Btn5D] == 1) {
	      if (pFlag == false) {
					pFlag = true;
					nMotorEncoder[LiftBL] = 0;
					nMotorEncoder[LiftBR] = 0;
					startTask(timer);
				}
				motor[LiftTL] = -127;
				motor[LiftBL] = -127;
				motor[LiftTR] = -127;
				motor[LiftBR] = -127;
			} else {
			  if (pFlag == true) {
					pFlag = false;
					stopTask(timer);
					getSpeed();
				}
				motor[LiftTL] = 0;
				motor[LiftBL] = 0;
				motor[LiftTR] = 0;
				motor[LiftBR] = 0;
			}
		}
  }
}
