#pragma config(Sensor, in1,    betaTest,       sensorAnalog)
#pragma config(Motor,  port2,           FL,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           BL,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           FR,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           BR,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           LiftTL,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           LiftBL,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           LiftTR,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           LiftBR,        tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"
#include "SongTasks.c" //Songs to be used in the program

int testVar = 1;
int lspeed;
int rspeed;
bool click = false;
bool check = false;
int seed = 0;
int step = 1;
int timeleft = 15000;
int timechosen;

void setRandomSeed() {
	clearLCDLine(0);
	clearLCDLine(1);
	check = false;
	click = false;
	while (check == false) {
		bLCDBacklight = true;									// Turn on LCD Backlight
		displayLCDPos(0,0);
		string display1;
		sprintf(display1, "SET RANDSEED");
		displayNextLCDString(display1);
		displayLCDPos(1,0);
		string display2;
		sprintf(display2, "SEED: %4d", seed);
		displayNextLCDString(display2);
		if (nLCDButtons == 1 && click == false) {
			click = true;
			seed = seed - 1;
		} else if (nLCDButtons == 4 && click == false) {
			click = true;
			seed = seed + 1;
		} else if (nLCDButtons == 2) {
			check = true;
		} else if (nLCDButtons == 0 && click == true) {
			click = false;
		}
	}
	clearLCDLine(0);
	clearLCDLine(1);
	bLCDBacklight = true;									// Turn on LCD Backlight
	displayLCDPos(0,0);
	string display1;
	sprintf(display1, "RANDSEED SET!");
	displayNextLCDString(display1);
	displayLCDPos(1,0);
	string display2;
	sprintf(display2, "SEED: %4d", seed);
	displayNextLCDString(display2);
}

void dumbAutonomous() {
	srand(seed);
	timeleft = 15000;
	startTask(smb3);
	while (timeleft > 0) {
		clearLCDLine(0);
		clearLCDLine(1);
		bLCDBacklight = true;									// Turn on LCD Backlight
		displayLCDPos(0,0);
		string display1;
		sprintf(display1, "RANDAUTO");
		displayNextLCDString(display1);
		displayLCDPos(1,0);
		string display2;
		sprintf(display2, "STEP: %2d", step);
		displayNextLCDString(display2);
		lspeed = random(254) - 127;
		rspeed = random(254) - 127;
		motor[BL] = lspeed;
		motor[FL] = lspeed;
		motor[BR] = rspeed;
		motor[FR] = rspeed;
		timechosen = random(timeleft);
		timeleft = timeleft - timechosen;
		wait1Msec(timechosen);
		step = step + 1;
	}
	motor[BL] = 0;
	motor[FL] = 0;
	motor[BR] = 0;
	motor[FR] = 0;
	clearLCDLine(0);
	clearLCDLine(1);
	bLCDBacklight = true;									// Turn on LCD Backlight
	displayLCDPos(0,0);
	string display1;
	sprintf(display1, "RANDAUTO");
	displayNextLCDString(display1);
	displayLCDPos(1,0);
	string display2;
	sprintf(display2, "COMPLETE");
	displayNextLCDString(display2);
}

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
  bStopTasksBetweenModes = true;
  if (SensorValue[betaTest] == 0) {
  	testVar = 0; //Enable beta features
  	//setRandomSeed();
    } else {
    testVar = 1; //Disable beta features
	}
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
  // ..........................................................................
  // Insert user code here.
  // ..........................................................................

  // Remove this function call once you have "real" code.
	soundPlay = true;
  startTask(pacman);
	//if (testVar == 0) {
 // 	dumbAutonomous();
	//}
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
	//Start tasks here
  soundPlay = true;
  startTask(pacman);
  while (true)
  {
		//Drive motor controls
		if (testVar == 1) { //Default tank controls
			motor[BL] = vexRT[Ch3];
			motor[FL] = vexRT[Ch3];
			motor[BR] = vexRT[Ch2];
			motor[FR] = vexRT[Ch2];
		} else { //Beta motion controls
			if (abs(vexRT[AccelX]) > abs(vexRT[AccelY])) { //Turning Activated
				motor[BL] = vexRT[AccelX];
				motor[FL] = vexRT[AccelX];
				motor[BR] = -vexRT[AccelX];
				motor[FR] = -vexRT[AccelX];
	 	  } else { //Moving Activated
		  	motor[BL] = -vexRT[AccelY];
				motor[FL] = -vexRT[AccelY];
				motor[BR] = -vexRT[AccelY];
				motor[FR] = -vexRT[AccelY];
			}
		}
		//Sound ctonrols
		if (soundPlay == false) {
			if (vexRT[Btn7L] == 1) {
				soundPlay = true;
				startTask(zelda);
			} else if (vexRT[Btn7D] == 1) {
				soundPlay = true;
				startTask(ffvii);
			}	else if (vexRT[Btn7R] == 1) {
				soundPlay = true;
				startTask(smb3);
		  } else if (vexRT[Btn8L] == 1) {
  			soundPlay = true;
  			startTask(smbdeath);
  		} else if (vexRT[Btn8R] == 1) {
  			soundPlay = true;
  			startTask(smw2_map);
			}	else if (vexRT[Btn8D] == 1) {
				soundPlay = true;
				startTask(dkc);
			}	else if (vexRT[Btn8U] == 1) {
		  	soundPlay = true;
		  	startTask(PokemonGO2);
			}
		}
		if (nVexRCReceiveState & vrXmit2) { //Enable partner controls
			motor[LiftTL] = vexRT[Ch3Xmtr2];
			motor[LiftBL] = vexRT[Ch3Xmtr2];
			motor[LiftTR] = vexRT[Ch3Xmtr2];
			motor[LiftBR] = vexRT[Ch3Xmtr2];
		}	else { //Single controls
			if (vexRT[Btn5U] == 1) {
				motor[LiftTL] = 127;
				motor[LiftBL] = 127;
				motor[LiftTR] = 127;
				motor[LiftBR] = 127;
			}	else if (vexRT[Btn5D] == 1) {
				motor[LiftTL] = -127;
				motor[LiftBL] = -127;
				motor[LiftTR] = -127;
				motor[LiftBR] = -127;
			} else {
				motor[LiftTL] = 0;
				motor[LiftBL] = 0;
				motor[LiftTR] = 0;
				motor[LiftBR] = 0;
			}
		}
  }
}
