#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    clawEnc,        sensorPotentiometer)
#pragma config(Sensor, in2,    liftEnc,        sensorPotentiometer)
#pragma config(Sensor, in8,    betaTest,       sensorAnalog)
#pragma config(Sensor, I2C_1,  rightWheelEncoder, sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  leftWheelEncoder, sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           BR,            tmotorVex393_HBridge, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port2,           FR,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           liftTR,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           liftMR,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           liftBLR,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           liftTL,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           liftML,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           claw,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           FL,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          BL,            tmotorVex393_HBridge, openLoop, encoderPort, I2C_2)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"
#include "SongTasks.c" //Songs to be used in the program

int testVar = 1;
//int lspeed;
//int rspeed;
int time = 0;
string line1 = "Autonomous 1";
string line2;
int mode = 0;
int mode2 = 0;
bool locked = true;
string linee1, linee2;
string mainBattery, backupBattery;

int automode = 1;
string side = "Left";
int turnDir = -1;
bool ready = false;
bool pressed = false;

int deadzone3;
int deadzone2;
int limit = 0;

int auSpeed = 25;
int debugSpeed = 50;
int drive1SquareEncVal = 400; //Need to test
int turn90DegEncVal;

float voltage = nImmediateBatteryLevel;

//bool click = false;
//bool check = false;
//int seed = 0;
//int step = 1;
//int timeleft = 15000;
//int timechosen;

//void setRandomSeed() {
//	clearLCDLine(0);
//	clearLCDLine(1);
//	check = false;
//	click = false;
//	while (check == false) {
//		bLCDBacklight = true;									// Turn on LCD Backlight
//		displayLCDPos(0,0);
//		string display1;
//		sprintf(display1, "SET RANDSEED");
//		displayNextLCDString(display1);
//		displayLCDPos(1,0);
//		string display2;
//		sprintf(display2, "SEED: %4d", seed);
//		displayNextLCDString(display2);
//		if (nLCDButtons == 1 && click == false) {
//			click = true;
//			seed = seed - 1;
//		} else if (nLCDButtons == 4 && click == false) {
//			click = true;
//			seed = seed + 1;
//		} else if (nLCDButtons == 2) {
//			check = true;
//		} else if (nLCDButtons == 0 && click == true) {
//			click = false;
//		}
//	}
//	clearLCDLine(0);
//	clearLCDLine(1);
//	bLCDBacklight = true;									// Turn on LCD Backlight
//	displayLCDPos(0,0);
//	string display1;
//	sprintf(display1, "RANDSEED SET!");
//	displayNextLCDString(display1);
//	displayLCDPos(1,0);
//	string display2;
//	sprintf(display2, "SEED: %4d", seed);
//	displayNextLCDString(display2);
//}

//void dumbAutonomous() {
//	srand(seed);
//	timeleft = 15000;
//	startTask(smb3);
//	while (timeleft > 0) {
//		clearLCDLine(0);
//		clearLCDLine(1);
//		bLCDBacklight = true;									// Turn on LCD Backlight
//		displayLCDPos(0,0);
//		string display1;
//		sprintf(display1, "RANDAUTO");
//		displayNextLCDString(display1);
//		displayLCDPos(1,0);
//		string display2;
//		sprintf(display2, "STEP: %2d", step);
//		displayNextLCDString(display2);
//		lspeed = random(254) - 127;
//		rspeed = random(254) - 127;
//		motor[BL] = lspeed;
//		motor[FL] = lspeed;
//		motor[BR] = rspeed;
//		motor[FR] = rspeed;
//		timechosen = random(timeleft);
//		timeleft = timeleft - timechosen;
//		wait1Msec(timechosen);
//		step = step + 1;
//	}
//	motor[BL] = 0;
//	motor[FL] = 0;
//	motor[BR] = 0;
//	motor[FR] = 0;
//	clearLCDLine(0);
//	clearLCDLine(1);
//	bLCDBacklight = true;									// Turn on LCD Backlight
//	displayLCDPos(0,0);
//	string display1;
//	sprintf(display1, "RANDAUTO");
//	displayNextLCDString(display1);
//	displayLCDPos(1,0);
//	string display2;
//	sprintf(display2, "COMPLETE");
//	displayNextLCDString(display2);
//}

task timer() {
	time = 0;
	while (true) {
		wait1Msec(1);
		time = time + 1;
	}
}

task preAutonData() {
	while (true) {
		bLCDBacklight = true;
		sprintf(line2, "Side: %5s", side);
		displayLCDPos(0, 0);
		displayNextLCDString(line1);
		displayLCDPos(1, 0);
		displayNextLCDString(line2);
	}
}

task encoderValues() {
	while (true) {
		clearLCDLine(0);
		clearLCDLine(1);
		displayLCDString(0, 0, "Claw: ");
		sprintf(linee1, "%4d", SensorValue[clawEnc]);
		displayNextLCDString(linee1);
		displayLCDString(1, 0, "DriveEnc: ");
		sprintf(linee2, "%4d", nMotorEncoder[rightWheelEncoder]);
		displayNextLCDString(linee2);
		wait1Msec(100);
	}
}

void moving(int sp) {
	motor[BR] = sp;
	motor[FR] = sp;
	motor[BL] = sp;
	motor[FL] = sp;
}

void turning(int sp) {
	motor[BR] = sp;
	motor[FR] = sp;
	motor[BL] = -sp;
	motor[FL] = -sp;
}

void right(int sp) {
	motor[BR] = sp;
	motor[FR] = sp;
}

void left(int sp) {
	motor[BL] = sp;
	motor[FL] = sp;
}

void lifting(int sp) {
	motor[liftTL] = sp;
	motor[liftML] = sp;
	motor[liftTR] = sp;
	motor[liftMR] = sp;
	motor[liftBLR] = sp;
}

void auto1() {
	moving(-127);
	wait1Msec(1500);
	moving(0);
	wait1Msec(500);
	lifting(-127);
	motor[claw] = 127;
	wait1Msec(1000);
	motor[claw] = 0;
	wait1Msec(1000);
	lifting(0);
}

void auto2() {

}

void auto3() {

}

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
	if (vexRT[Btn5D] == 1 || vexRT[Btn5U] == 1 || vexRT[Btn6D] == 1 || vexRT[Btn6U] == 1) {
	}	//Skip bootup
	else {
	SensorType[clawEnc] = sensorNone;
	SensorType[liftEnc] = sensorNone;
	wait1Msec(1000);
	SensorType[clawEnc] = sensorPotentiometer;
	SensorType[liftEnc] = sensorPotentiometer;
	clearDebugStream();
	bStopTasksBetweenModes = true;
	if (SensorValue[betaTest] == 0) {
		testVar = 0; //Enable beta features
		//setRandomSeed();
		} else {
		testVar = 1; //Disable beta features
	}
	//Reset controller
	deadzone2 = vexRT[Ch2];
	deadzone3 = vexRT[Ch3];
	//Reset encoders
	nMotorEncoder[BR] = 0;
	nMotorEncoder[BL] = 0;
	//Reset motors
	motor[BL] = 0;
	motor[BR] = 0;
	motor[FL] = 0;
	motor[FR] = 0;
	clearLCDLine(0);
	clearLCDLine(1);
	bLCDBacklight = true;
	//Show battery data before match
	displayLCDString(0, 0, "Primary: ");
	sprintf(mainBattery, "%1.2f%c", nImmediateBatteryLevel/1000.0,'V'); //Build the value to be displayed
	displayNextLCDString(mainBattery);
	displayLCDString(1, 0, "Backup: ");
	sprintf(backupBattery, "%1.2f%c", BackupBatteryLevel/1000.0, 'V');    //Build the value to be displayed
	displayNextLCDString(backupBattery);
	wait1Msec(2000);
	clearLCDLine(0);
	clearLCDLine(1);
	startTask(preAutonData);
	startTask(timer);
	while (ready == false) {
		if (time > 3000) { //Failsafe, normally 3000
			ready = true;
		}
		if (nLCDButtons == 1 && pressed == false) {
			pressed = true;
			automode = automode + 1;
			if (automode == 4) {
				automode = 1;
			}
			if (automode == 1) {
				line1 = "Autonomous 1";
				}	else if (automode == 2) {
				line1 = "Autonomous 2";
				} else if (automode == 3) {
				line1 = "Autonomous 3";
			}
			clearLCDLine(0);
			clearLCDLine(1);
			}	else if (nLCDButtons == 2 && pressed == false) {
			pressed = true;
			if (side == "Left") {
				side = "Right";
				}	else {
				side = "Left";
			}
			turnDir = -turnDir;
			clearLCDLine(0);
			clearLCDLine(1);
			}	else if (nLCDButtons == 4 && pressed == false) {
			pressed = true;
			ready = true;
			}	else if (nLCDButtons == 0 && pressed == true) {
			pressed = false;
		}
	}
	stopTask(preAutonData);
	stopTask(timer);
	bLCDBacklight = true;
	clearLCDLine(0);
	clearLCDLine(1);
	if ((time % 10) <= 3) {
		sprintf(line1, "AUTO SET!");
		sprintf(line2, "READY");
		}	else if ((time % 10) <= 5) {
		sprintf(line1, "AUTO GET!");
		sprintf(line2, "REEFY");
		}	else if ((time % 10) <= 7) {
		sprintf(line1, "SET AUTO!");
		sprintf(line2, "GRAVY");
		}	else if ((time % 10) <= 8) {
		sprintf(line1, "SORRY BRO!");
		sprintf(line2, "- YOUNG");
		}	else if ((time % 10) <= 9) {
		sprintf(line1, "HEY, THAT'S");
		sprintf(line2, "PRETTY GOOD!");
	}
	displayLCDPos(0, 0);
	displayNextLCDString(line1);
	displayLCDPos(1, 0);
	displayNextLCDString(line2);
	wait1Msec(2000);
	clearLCDLine(0);
	clearLCDLine(1);
	}
	playSound(soundBlip);
	playSound(soundException);
	playSound(soundBeepBeep);
	playSound(soundLowBuzz);
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
	stopTask(timer);
	//startTask(timer);
	startTask(encoderValues);
	startTask(pacman);
	//Reset encoders
	nMotorEncoder[BR] = 0;
	nMotorEncoder[BL] = 0;
	soundPlay = true;
	//startTask(placeholder);
	if (automode == 1) { //Drive forward
		auto1();
		}	else if (automode == 2) { //Middle stars
		auto2();
		} else if (automode == 3) { //CUBE
		auto3();
		} else {
		auto1();
	}
	stopTask(pacman);
	soundPlay = true;
	startTask(smbdeath);
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
	clearDebugStream();
	stopTask(timer);
	startTask(encoderValues);
	//Reset encoders
	nMotorEncoder[BR] = 0;
	nMotorEncoder[BL] = 0;
	//Reset motors
	motor[BL] = 0;
	motor[BR] = 0;
	motor[FL] = 0;
	motor[FR] = 0;
	//Start tasks here
	stopTask(timer);
	startTask(timer);
	soundPlay = true;
	startTask(balloon);
	while (true)
	{

		//Claw controls
		if (vexRT[Btn5U] == 1) {
			motor[claw] = 127;
		}	else if (vexRT[Btn6U] == 1) {
			motor[claw] = -127;
		} else {
			motor[claw] = 0;
		}

		//Lift controls
		if (vexRT[Btn5D] == 1) {
			motor[liftTL] = 127;
			motor[liftML] = 127;
			motor[liftTR] = 127;
			motor[liftMR] = 127;
			motor[liftBLR] = 127;
		}	else if (vexRT[Btn6D] == 1) {
			motor[liftTL] = -127;
			motor[liftML] = -127;
			motor[liftTR] = -127;
			motor[liftMR] = -127;
			motor[liftBLR] = -127;
		} else {
			motor[liftTL] = 0;
			motor[liftML] = 0;
			motor[liftTR] = 0;
			motor[liftMR] = 0;
			motor[liftBLR] = 0;
		}

		//Drive motor controls
		if (vexRT[Btn8D] == 0 && vexRT[Btn8U] == 0 && vexRT[Btn8L] == 0 && vexRT[Btn8R] == 0) {
			if (testVar == 1) {
				if (abs(vexRT[Ch3]) <= abs(deadzone3)) {
					motor[BL] = 0;
					motor[FL] = 0;
					}	else {
					motor[BL] = vexRT[Ch3];
					motor[FL] = vexRT[Ch3];
				}
				if (abs(vexRT[Ch2]) <= abs(deadzone2)) {
					motor[BR] = 0;
					motor[FR] = 0;
					} else {
					motor[BR] = vexRT[Ch2];
					motor[FR] = vexRT[Ch2];
				}
				} else { //Motion controls
				if (abs(vexRT[AccelX]) > abs(vexRT[AccelY])) { //Turning Activated
					motor[BL] = vexRT[AccelX];
					motor[FL] = vexRT[AccelX];
					motor[BR] = -vexRT[AccelX];
					motor[FR] = -vexRT[AccelX];
					} else { //Moving Activated
					motor[BL] = -vexRT[AccelY];
					motor[FL] = -vexRT[AccelY];
					motor[BR] = -vexRT[AccelY];
					motor[FR] = -vexRT[AccelY];
				}
			}
		}
		//Sound controls
		if (soundPlay == false) {
			if (vexRT[Btn7R] == 1) {
				soundPlay = true;
				startTask(PokemonGO2);
				} else if (vexRT[Btn7D] == 1) {
				soundPlay = true;
				startTask(PPAP);
			} else if (vexRT[Btn7L] == 1) {
				soundPlay = true;
				startTask(smb3);
			} else if (vexRT[Btn7U] == 1) {
				soundPlay = true;
				startTask(smw2_map);
			}
		}
		if (vexRT[Btn8D] == 1) {
			mode = 1;
			motor[BR] = -127;
			motor[BL] = -127;
			motor[FL] = -127;
			motor[FR] = -127;
			while (abs(nMotorEncoder[BR]) < drive1SquareEncVal) {
			}
			nMotorEncoder[BR] = 0;
			motor[BR] = 0;
			motor[BL] = 0;
			motor[FL] = 0;
			motor[FR] = 0;
			}	else if (vexRT[Btn8U] == 1) {
			mode = 2;
			motor[BR] = 127;
			motor[BL] = 127;
			motor[FL] = 127;
			motor[FR] = 127;
			while (abs(nMotorEncoder[BR]) < drive1SquareEncVal) {
			}
			nMotorEncoder[BR] = 0;
			motor[BR] = 0;
			motor[BL] = 0;
			motor[FL] = 0;
			motor[FR] = 0;
			}	else if (vexRT[Btn8L] == 1) {
			mode = 3;
			turning(-debugSpeed);
			} else if (vexRT[Btn8R] == 1) {
			mode = 4;
			turning(debugSpeed);
			} else { //AutoGenerator
			if (mode != 0) {
				if (mode == 1) {
					writeDebugStreamLine("while (nMotorEncoder[BR] > %d) {", nMotorEncoder[BR]);
					writeDebugStreamLine("	moving(-auSpeed);");
					writeDebugStreamLine("}");
					writeDebugStreamLine("moving(0);");
					writeDebugStreamLine("wait1Msec(100);");
					}	else if (mode == 2) {
					writeDebugStreamLine("while (nMotorEncoder[BR] < %d) {", nMotorEncoder[BR]);
					writeDebugStreamLine("	moving(auSpeed);");
					writeDebugStreamLine("}");
					writeDebugStreamLine("moving(0);");
					writeDebugStreamLine("wait1Msec(100);");
					} else if (mode == 3) {
					writeDebugStreamLine("while (nMotorEncoder[BR] < %d) {", nMotorEncoder[BR]);
					writeDebugStreamLine("	right(auSpeed);");
					writeDebugStreamLine("}");
					writeDebugStreamLine("right(0);");
					writeDebugStreamLine("wait1Msec(100);");
					} else if (mode == 4) {
					writeDebugStreamLine("while (nMotorEncoder[BL] < %d) {", nMotorEncoder[BL]);
					writeDebugStreamLine("	left(auSpeed);");
					writeDebugStreamLine("}");
					writeDebugStreamLine("left(0);");
					writeDebugStreamLine("wait1Msec(100);");
				}
				mode = 0;
			}
		}
	}
}
