#pragma config(Motor,  port4,           FL,            tmotorVex393, openLoop)
#pragma config(Motor,  port5,           FR,            tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port6,           BL,            tmotorVex393, openLoop)
#pragma config(Motor,  port7,           BR,            tmotorVex393, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(15)
#pragma userControlDuration(145)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
  // Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{

}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	while (true)
	{
		if (abs(vexRT[AccelX]) > abs(vexRT[AccelY])) //if absolute value of LR > absolute value of UD
				{
				motor[BR] = -(vexRT[AccelX]); //LR is the chosen control
				motor[FR] = -(vexRT[AccelX]); //right side is inverted speed of LR
				motor[BL] = vexRT[AccelX]; //left side isnt inverted
				motor[FL] = vexRT[AccelX]; //so that it turns in direction of LR
				}
				else if (abs(vexRT[AccelY]) >= abs(vexRT[AccelX])) //if absolute value of LR <= absolute value of UD
				{
				motor[BR] = -vexRT[AccelY]; //UD is the chosen control
				motor[FR] = -vexRT[AccelY]; //drive forwards/backwards at UD speed
				motor[BL] = -vexRT[AccelY];
				motor[FL] = -vexRT[AccelY];
		}
	}
}
