#pragma config(UART_Usage, UART2, uartVEXLCD, baudRate19200, IOPins, None, None)
//*!!Code automatically generated by 'ROBOTC' configuration wizard							 !!*//

/**************************/
/* Possible combinations: */
/*                        */
/* Binary   Decimal   Btn */
/**************************/
/* 000        0       --- */
/* 001        1       L-- */
/* 010        2       -C- */
/* 011        3       LC- */
/* 100        4       --R */
/* 101        5       L-R */
/* 110        6       -CR */
/* 111        7       LCR */
/**************************/

task main()
{
	bLCDBacklight = true;									// Turn on LCD Backlight
	string mainBattery, backupBattery;

	int auto = 1;
	int message = random(2);
	// Clear LCD Lines
  clearLCDLine(0);
  clearLCDLine(1);

  // Top LCD Line Display Stuff:
  displayLCDPos(0,0);
  displayNextLCDString("Auto");
  displayNextLCDChar(' ');
  displayNextLCDChar(':');
  displayNextLCDChar(' ');
  while(true)
  {
    if (nLCDButtons == 1) { // left
    	auto = 1;
    }	else if (nLCDButtons == 2) { // center
      auto = 2;
    } else if (nLCDButtons == 4) { // right
      auto = 4;
    }

    displayLCDPos(0,8);
    if (auto == 1) { // left
    	displayNextLCDString("Generic");
    }	else if (auto == 2) { // center
      displayNextLCDString("Adv Red");
    } else if (auto == 4) { // right
      displayNextLCDString("Adv Blu");
    }

    // Bottom LCD Line Display Stuff for when the match begins:
    //displayLCDPos(1,0);
    //if (message == 0) {
    //	displayNextLCDString("do you even lift");
    //}	else if (message == 1) {
    //  displayNextLCDString("urCubesBelong2Us");
    //} else if (message == 2) {
    //  displayNextLCDString("come on and slam");
    //}

    displayLCDPos(1,0);
    displayNextLCDString("P:");
    sprintf(mainBattery, "%1.2f%c", nImmediateBatteryLevel/1000.0,'V'); //Build the value to be displayed
		displayNextLCDString(mainBattery);
		displayNextLCDString(" B:");
		sprintf(backupBattery, "%1.2f%c", BackupBatteryLevel/1000.0, 'V');	//Build the value to be displayed
		displayNextLCDString(backupBattery);

    // Wait a little to keep the screen refreshing smoothly:
    wait1Msec(100);
  }
}
