#pragma config(Motor,  port2,           ALT,           tmotorVex393, openLoop)
#pragma config(Motor,  port3,           ALB,           tmotorVex393, openLoop)
#pragma config(Motor,  port4,           FL,            tmotorVex393, openLoop)
#pragma config(Motor,  port5,           FR,            tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port6,           BL,            tmotorVex393, openLoop)
#pragma config(Motor,  port7,           BR,            tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port8,           ARB,           tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port9,           ART,           tmotorVex393, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
  // Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
  motor[FL] = 127;
	motor[BL] = 127;
	motor[BR] = 127;
	motor[FR] = 127;
	wait1Msec(1000);
	motor[FL] = 0;
	motor[BL] = 0;
	motor[BR] = 0;
	motor[FR] = 0;
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	while (true)
	{
	  motor[FL]= vexRT[Ch3];
	  motor[FR]=vexRT[Ch2];
	  motor[BL]=vexRT[Ch3];
	  motor[BR]=vexRT[Ch2];

	 if (vexRT[Ch3Xmtr2]==1)
	 {
	   motor[ALB]=127;
	   motor[ALT]=127;
		 motor[ARB]=127;
		 motor[ART]=127;
			}
		else
			{
		 motor[ALB]=0;
	   motor[ALT]=0;
		 motor[ARB]=0;
		 motor[ART]=0;
		}
	}
}
