#pragma config(Sensor, dgtl3,  sonar,          sensorSONAR_cm)
#pragma config(Motor,  port2,           FL,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           BL,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           FR,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           BR,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          flashlight,    tmotorVexFlashlight, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
float pitch = 0.25;
int bpm = 120; //BEATS PER MINUTE
int spm = 600; //STROBE PER MINUTE
//timing = 60000/bpm
//TODO:
//Add LCD
//Let LCD Buttons or controller control variables
//Strobe light

task music () {
	int ignore = SensorValue[sonar];
	while (true) {
		if(bSoundQueueAvailable && SensorValue[sonar] < ignore) // if there is still space in the Sound Queue:
		{
			playImmediateTone(round((abs(SensorValue[sonar])*pitch)/10), 50);  // play tone according to sensor readings
			wait1Msec((60000/bpm));
		}
	}
}

task debug () {
	clearLCDLine(0);
	clearLCDLine(1);
	while (true) {
		bLCDBacklight = true;									// Turn on LCD Backlight
		displayLCDPos(0,0);
		string display1;
		sprintf(display1, "BPM: %3d STR: %3d", bpm, spm);
		displayNextLCDString(display1);
		displayLCDPos(1,0);
		string display2;
		sprintf(display2, "PITCH: %3d", pitch);
		displayNextLCDString(display2);
	}
}

task bpmConfig () {
	clearLCDLine(0);
	clearLCDLine(1);
	while (true) {
		bLCDBacklight = true;									// Turn on LCD Backlight
		displayLCDPos(0,0);
		string display1;
		sprintf(display1, " CONFIGURE  BPM ");
		displayNextLCDString(display1);
		displayLCDPos(1,0);
		string display2;
		sprintf(display2, "    BPM: %3d    ", bpm);
		displayNextLCDString(display2);
	}
}

task spmConfig () {
	clearLCDLine(0);
	clearLCDLine(1);
	while (true) {
		bLCDBacklight = true;									// Turn on LCD Backlight
		displayLCDPos(0,0);
		string display1;
		sprintf(display1, "CONFIGURE STROBE");
		displayNextLCDString(display1);
		displayLCDPos(1,0);
		string display2;
		sprintf(display2, "STROBE RATE: %3d", spm);
		displayNextLCDString(display2);
	}
}

task pitchConfig () {
	clearLCDLine(0);
	clearLCDLine(1);
	while (true) {
		bLCDBacklight = true;									// Turn on LCD Backlight
		displayLCDPos(0,0);
		string display1;
		sprintf(display1, "CONFIGURE  PITCH");
		displayNextLCDString(display1);
		displayLCDPos(1,0);
		string display2;
		sprintf(display2, "   PITCH: %3d   ", pitch);
		displayNextLCDString(display2);
	}
}

task strobe() {
	while (true) {
		motor[flashlight] = 127;
		wait1Msec(60000/spm);
		motor[flashlight] = 0;
		wait1Msec(60000/spm);
	}
}

void tank() {
	motor[FL] = vexRT[Ch3];
	motor[BL] = vexRT[Ch3];
	motor[FR] = vexRT[Ch2];
	motor[BR] = vexRT[Ch2];
}

task main()
{
	startTask(strobe);
	startTask(music);
	startTask(debug);
	while (true) {
		tank();
		if
	}
}
