#pragma config(Sensor, in3,    line,           sensorLineFollower)
#pragma config(Sensor, dgtl3,  sonar,          sensorSONAR_cm)
#pragma config(Motor,  port2,           FL,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           BL,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           FR,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           BR,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          flashlight,    tmotorVexFlashlight, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define ARRAYSIZE(a) (sizeof(a)/sizeof(a[0]))
int pitch = 25;
int count = 1;
int CHANGE = 50; //CHANGE SPEED
int bpm = 120; //BEATS PER MINUTE
int spm = 100; //STROBE PER MINUTE
string power = "off";
string recordS = "ready";
float rec[100][5];
int recBpm[100][5];
string rec2[100][5];
string mode = "debug";
string prevMode = "debug";
string d1;
string d2;
int rData = 0;
int curData = 0;

void message () {
	clearLCDLine(0);
	clearLCDLine(1);
		bLCDBacklight = true;									// Turn on LCD Backlight
		displayLCDPos(0,0);
		displayNextLCDString(d1);
		displayLCDPos(1,0);
		displayNextLCDString(d2);
}

//timing = 60000/bpm
//TODO:
//UPLOAD SONGS AND CONFIG THEM TO BUTTONS (SEE BOOKMARKS)
//Upload chiptune config
//Add alerts
//Be able to turn off light (switch!!!)
//Get wheels/motors
//Add recorder [Done-ish, need to add alert]

void smb_under()
{
  //        100 = Tempo
  //          6 = Default octave
  //    Quarter = Default note length
  //        10% = Break between notes
  //
  PlayTone(  784,    7); wait1Msec(  75);  // Note(C, Duration(32th))
  PlayTone(    0,    7); wait1Msec(  75);  // Note(Rest, Duration(32th))
  PlayTone( 1046,    7); wait1Msec(  75);  // Note(C7, Duration(32th))
  PlayTone(    0,    7); wait1Msec(  75);  // Note(Rest, Duration(32th))
  PlayTone(  880,    7); wait1Msec(  75);  // Note(A5, Duration(32th))
  PlayTone(    0,    7); wait1Msec(  75);  // Note(Rest, Duration(32th))
  PlayTone( 1320,    7); wait1Msec(  75);  // Note(A, Duration(32th))
  PlayTone(    0,    7); wait1Msec(  75);  // Note(Rest, Duration(32th))
  PlayTone(  932,    7); wait1Msec(  75);  // Note(A#5, Duration(32th))
  PlayTone(    0,    7); wait1Msec(  75);  // Note(Rest, Duration(32th))
  PlayTone( 1398,    7); wait1Msec(  75);  // Note(A#, Duration(32th))
  PlayTone(    0,  108); wait1Msec(1200);  // Note(Rest, Duration(Half))
  PlayTone(  784,    7); wait1Msec(  75);  // Note(C, Duration(32th))
  PlayTone(    0,    7); wait1Msec(  75);  // Note(Rest, Duration(32th))
  PlayTone( 1046,    7); wait1Msec(  75);  // Note(C7, Duration(32th))
  PlayTone(    0,    7); wait1Msec(  75);  // Note(Rest, Duration(32th))
  PlayTone(  880,    7); wait1Msec(  75);  // Note(A5, Duration(32th))
  PlayTone(    0,    7); wait1Msec(  75);  // Note(Rest, Duration(32th))
  PlayTone( 1320,    7); wait1Msec(  75);  // Note(A, Duration(32th))
  PlayTone(    0,    7); wait1Msec(  75);  // Note(Rest, Duration(32th))
  PlayTone(  932,    7); wait1Msec(  75);  // Note(A#5, Duration(32th))
  PlayTone(    0,    7); wait1Msec(  75);  // Note(Rest, Duration(32th))
  PlayTone( 1398,    7); wait1Msec(  75);  // Note(A#, Duration(32th))
  PlayTone(    0,  108); wait1Msec(1200);  // Note(Rest, Duration(Half))
  PlayTone(  698,    7); wait1Msec(  75);  // Note(F5, Duration(32th))
  PlayTone(    0,    7); wait1Msec(  75);  // Note(Rest, Duration(32th))
  PlayTone( 1047,    7); wait1Msec(  75);  // Note(F, Duration(32th))
  PlayTone(    0,    7); wait1Msec(  75);  // Note(Rest, Duration(32th))
  PlayTone(  587,    7); wait1Msec(  75);  // Note(D5, Duration(32th))
  PlayTone(    0,    7); wait1Msec(  75);  // Note(Rest, Duration(32th))
  PlayTone(  880,    7); wait1Msec(  75);  // Note(D, Duration(32th))
  PlayTone(    0,    7); wait1Msec(  75);  // Note(Rest, Duration(32th))
  PlayTone(  622,    7); wait1Msec(  75);  // Note(D#5, Duration(32th))
  PlayTone(    0,    7); wait1Msec(  75);  // Note(Rest, Duration(32th))
  PlayTone(  933,    7); wait1Msec(  75);  // Note(D#, Duration(32th))
  PlayTone(    0,  108); wait1Msec(1200);  // Note(Rest, Duration(Half))
  PlayTone(  698,    7); wait1Msec(  75);  // Note(F5, Duration(32th))
  PlayTone(    0,    7); wait1Msec(  75);  // Note(Rest, Duration(32th))
  PlayTone( 1047,    7); wait1Msec(  75);  // Note(F, Duration(32th))
  PlayTone(    0,    7); wait1Msec(  75);  // Note(Rest, Duration(32th))
  PlayTone(  587,    7); wait1Msec(  75);  // Note(D5, Duration(32th))
  PlayTone(    0,    7); wait1Msec(  75);  // Note(Rest, Duration(32th))
  PlayTone(  880,    7); wait1Msec(  75);  // Note(D, Duration(32th))
  PlayTone(    0,    7); wait1Msec(  75);  // Note(Rest, Duration(32th))
  PlayTone(  622,    7); wait1Msec(  75);  // Note(D#5, Duration(32th))
  PlayTone(    0,    7); wait1Msec(  75);  // Note(Rest, Duration(32th))
  PlayTone(  933,    7); wait1Msec(  75);  // Note(D#, Duration(32th))
  return;
}

void smw_title()
{
  //        125 = Tempo
  //          5 = Default octave
  //    Quarter = Default note length
  //        10% = Break between notes
  //
  PlayTone( 1174,   22); wait1Msec( 240);  // Note(D7, Duration(Eighth))
  PlayTone( 1174,   22); wait1Msec( 240);  // Note(D7, Duration(Eighth))
  PlayTone( 1174,   22); wait1Msec( 240);  // Note(D7, Duration(Eighth))
  PlayTone(  880,   22); wait1Msec( 240);  // Note(D6, Duration(Eighth))
  PlayTone( 1174,   22); wait1Msec( 240);  // Note(D7, Duration(Eighth))
  PlayTone( 1174,   22); wait1Msec( 240);  // Note(D7, Duration(Eighth))
  PlayTone( 1174,   22); wait1Msec( 240);  // Note(D7, Duration(Eighth))
  PlayTone(  880,   22); wait1Msec( 240);  // Note(D6, Duration(Eighth))
  PlayTone( 1244,   86); wait1Msec( 960);  // Note(D#7, Duration(Half))
  PlayTone( 1174,   22); wait1Msec( 240);  // Note(D7, Duration(Eighth))
  PlayTone(    0,   43); wait1Msec( 480);  // Note(Rest)
  PlayTone(    0,    5); wait1Msec(  60);  // Note(Rest, Duration(32th))
  PlayTone(  880,   22); wait1Msec( 240);  // Note(D6, Duration(Eighth))
  PlayTone( 1481,   22); wait1Msec( 240);  // Note(B6, Duration(Eighth))
  PlayTone( 1481,   22); wait1Msec( 240);  // Note(B6, Duration(Eighth))
  PlayTone( 1481,   22); wait1Msec( 240);  // Note(B6, Duration(Eighth))
  PlayTone(  880,   22); wait1Msec( 240);  // Note(D6, Duration(Eighth))
  PlayTone( 1481,   22); wait1Msec( 240);  // Note(B6, Duration(Eighth))
  PlayTone( 1481,   22); wait1Msec( 240);  // Note(B6, Duration(Eighth))
  PlayTone( 1481,   22); wait1Msec( 240);  // Note(B6, Duration(Eighth))
  PlayTone(  880,   22); wait1Msec( 240);  // Note(D6, Duration(Eighth))
  PlayTone( 1481,   22); wait1Msec( 240);  // Note(B6, Duration(Eighth))
  PlayTone( 1481,   22); wait1Msec( 240);  // Note(B6, Duration(Eighth))
  PlayTone( 1481,   22); wait1Msec( 240);  // Note(B6, Duration(Eighth))
  PlayTone( 1481,   11); wait1Msec( 120);  // Note(B6, Duration(16th))
  PlayTone( 1046,   11); wait1Msec( 120);  // Note(C7, Duration(16th))
  PlayTone( 1481,   43); wait1Msec( 480);  // Note(B6)
  PlayTone( 1320,   22); wait1Msec( 240);  // Note(A6, Duration(Eighth))
  PlayTone(  880,   22); wait1Msec( 240);  // Note(D6, Duration(Eighth))
  PlayTone( 1320,   22); wait1Msec( 240);  // Note(A6, Duration(Eighth))
  PlayTone( 1320,   22); wait1Msec( 240);  // Note(A6, Duration(Eighth))
  PlayTone( 1320,   22); wait1Msec( 240);  // Note(A6, Duration(Eighth))
  PlayTone(  880,   22); wait1Msec( 240);  // Note(D6, Duration(Eighth))
  PlayTone( 1320,   22); wait1Msec( 240);  // Note(A6, Duration(Eighth))
  PlayTone( 1320,   22); wait1Msec( 240);  // Note(A6, Duration(Eighth))
  PlayTone( 1320,   22); wait1Msec( 240);  // Note(A6, Duration(Eighth))
  PlayTone(  880,   22); wait1Msec( 240);  // Note(D6, Duration(Eighth))
  PlayTone( 1320,   22); wait1Msec( 240);  // Note(A6, Duration(Eighth))
  PlayTone( 1320,   22); wait1Msec( 240);  // Note(A6, Duration(Eighth))
  PlayTone( 1320,   22); wait1Msec( 240);  // Note(A6, Duration(Eighth))
  PlayTone( 1320,   11); wait1Msec( 120);  // Note(A6, Duration(16th))
  PlayTone( 1481,   11); wait1Msec( 120);  // Note(B6, Duration(16th))
  PlayTone( 1320,   43); wait1Msec( 480);  // Note(A6)
  PlayTone( 1175,   22); wait1Msec( 240);  // Note(G6, Duration(Eighth))
  PlayTone(  880,   22); wait1Msec( 240);  // Note(D6, Duration(Eighth))
  PlayTone( 1481,   22); wait1Msec( 240);  // Note(B6, Duration(Eighth))
  PlayTone( 1481,   22); wait1Msec( 240);  // Note(B6, Duration(Eighth))
  PlayTone( 1481,   22); wait1Msec( 240);  // Note(B6, Duration(Eighth))
  PlayTone(  880,   22); wait1Msec( 240);  // Note(D6, Duration(Eighth))
  PlayTone( 1481,   22); wait1Msec( 240);  // Note(B6, Duration(Eighth))
  PlayTone( 1481,   22); wait1Msec( 240);  // Note(B6, Duration(Eighth))
  PlayTone( 1481,   22); wait1Msec( 240);  // Note(B6, Duration(Eighth))
  PlayTone(  880,   22); wait1Msec( 240);  // Note(D6, Duration(Eighth))
  PlayTone( 1481,   22); wait1Msec( 240);  // Note(B6, Duration(Eighth))
  PlayTone( 1481,   22); wait1Msec( 240);  // Note(B6, Duration(Eighth))
  PlayTone( 1481,   22); wait1Msec( 240);  // Note(B6, Duration(Eighth))
  PlayTone( 1320,   11); wait1Msec( 120);  // Note(A6, Duration(16th))
  PlayTone( 1481,   11); wait1Msec( 120);  // Note(B6, Duration(16th))
  PlayTone( 1046,   43); wait1Msec( 480);  // Note(C7)
  PlayTone( 1318,   43); wait1Msec( 480);  // Note(E7)
  PlayTone( 1174,   22); wait1Msec( 240);  // Note(D7, Duration(Eighth))
  PlayTone( 1174,   22); wait1Msec( 240);  // Note(D7, Duration(Eighth))
  PlayTone( 1174,   22); wait1Msec( 240);  // Note(D7, Duration(Eighth))
  PlayTone(  880,   22); wait1Msec( 240);  // Note(D6, Duration(Eighth))
  PlayTone( 1046,   22); wait1Msec( 240);  // Note(C7, Duration(Eighth))
  PlayTone( 1046,   22); wait1Msec( 240);  // Note(C7, Duration(Eighth))
  PlayTone( 1046,   22); wait1Msec( 240);  // Note(C7, Duration(Eighth))
  PlayTone( 1109,   22); wait1Msec( 240);  // Note(F#6, Duration(Eighth))
  PlayTone( 1175,   86); wait1Msec( 960);  // Note(G6, Duration(Half))
  return;
}

void ffvii_boss()
{
  //        112 = Tempo
  //          5 = Default octave
  //    Quarter = Default note length
  //        10% = Break between notes
  //
  PlayTone(  440,   12); wait1Msec( 134);  // Note(A4, Duration(16th))
  PlayTone(  440,   12); wait1Msec( 134);  // Note(A4, Duration(16th))
  PlayTone(  440,   12); wait1Msec( 134);  // Note(A4, Duration(16th))
  PlayTone(  523,   36); wait1Msec( 402);  // Note(C, Duration(Eighth .))
  PlayTone(  440,   12); wait1Msec( 134);  // Note(A4, Duration(16th))
  PlayTone(  440,   12); wait1Msec( 134);  // Note(A4, Duration(16th))
  PlayTone(  440,   12); wait1Msec( 134);  // Note(A4, Duration(16th))
  PlayTone(  587,   36); wait1Msec( 402);  // Note(D, Duration(Eighth .))
  PlayTone(  440,   12); wait1Msec( 134);  // Note(A4, Duration(16th))
  PlayTone(  440,   12); wait1Msec( 134);  // Note(A4, Duration(16th))
  PlayTone(  440,   12); wait1Msec( 134);  // Note(A4, Duration(16th))
  PlayTone(  622,   12); wait1Msec( 134);  // Note(D#, Duration(16th))
  PlayTone(  587,   12); wait1Msec( 134);  // Note(D, Duration(16th))
  PlayTone(  523,   12); wait1Msec( 134);  // Note(C, Duration(16th))
  PlayTone(  587,   12); wait1Msec( 134);  // Note(D, Duration(16th))
  PlayTone(  523,   12); wait1Msec( 134);  // Note(C, Duration(16th))
  PlayTone(  493,   12); wait1Msec( 134);  // Note(B4, Duration(16th))
  PlayTone(  523,   24); wait1Msec( 268);  // Note(C, Duration(Eighth))
  PlayTone(  493,   12); wait1Msec( 134);  // Note(B4, Duration(16th))
  PlayTone(  440,   12); wait1Msec( 134);  // Note(A4, Duration(16th))
  PlayTone(  440,   12); wait1Msec( 134);  // Note(A4, Duration(16th))
  PlayTone(  440,   12); wait1Msec( 134);  // Note(A4, Duration(16th))
  PlayTone(  523,   36); wait1Msec( 402);  // Note(C, Duration(Eighth .))
  PlayTone(  440,   12); wait1Msec( 134);  // Note(A4, Duration(16th))
  PlayTone(  440,   12); wait1Msec( 134);  // Note(A4, Duration(16th))
  PlayTone(  440,   12); wait1Msec( 134);  // Note(A4, Duration(16th))
  PlayTone(  587,   36); wait1Msec( 402);  // Note(D, Duration(Eighth .))
  PlayTone(  440,   12); wait1Msec( 134);  // Note(A4, Duration(16th))
  PlayTone(  440,   12); wait1Msec( 134);  // Note(A4, Duration(16th))
  PlayTone(  440,   12); wait1Msec( 134);  // Note(A4, Duration(16th))
  PlayTone(  622,   12); wait1Msec( 134);  // Note(D#, Duration(16th))
  PlayTone(  587,   12); wait1Msec( 134);  // Note(D, Duration(16th))
  PlayTone(  523,   12); wait1Msec( 134);  // Note(C, Duration(16th))
  PlayTone(  587,   12); wait1Msec( 134);  // Note(D, Duration(16th))
  PlayTone(  523,   12); wait1Msec( 134);  // Note(C, Duration(16th))
  PlayTone(  493,   12); wait1Msec( 134);  // Note(B4, Duration(16th))
  PlayTone(  523,   24); wait1Msec( 268);  // Note(C, Duration(Eighth))
  PlayTone(  493,   12); wait1Msec( 134);  // Note(B4, Duration(16th))
  PlayTone(  523,   12); wait1Msec( 134);  // Note(C, Duration(16th))
  PlayTone(  523,   12); wait1Msec( 134);  // Note(C, Duration(16th))
  PlayTone(  523,   12); wait1Msec( 134);  // Note(C, Duration(16th))
  PlayTone(  622,   36); wait1Msec( 402);  // Note(D#, Duration(Eighth .))
  PlayTone(  523,   12); wait1Msec( 134);  // Note(C, Duration(16th))
  PlayTone(  523,   12); wait1Msec( 134);  // Note(C, Duration(16th))
  PlayTone(  523,   12); wait1Msec( 134);  // Note(C, Duration(16th))
  PlayTone(  698,   36); wait1Msec( 402);  // Note(F, Duration(Eighth .))
  PlayTone(  523,   12); wait1Msec( 134);  // Note(C, Duration(16th))
  PlayTone(  523,   12); wait1Msec( 134);  // Note(C, Duration(16th))
  PlayTone(  523,   12); wait1Msec( 134);  // Note(C, Duration(16th))
  PlayTone(  739,   12); wait1Msec( 134);  // Note(F#, Duration(16th))
  PlayTone(  698,   12); wait1Msec( 134);  // Note(F, Duration(16th))
  PlayTone(  622,   12); wait1Msec( 134);  // Note(D#, Duration(16th))
  PlayTone(  698,   12); wait1Msec( 134);  // Note(F, Duration(16th))
  PlayTone(  622,   12); wait1Msec( 134);  // Note(D#, Duration(16th))
  PlayTone(  587,   12); wait1Msec( 134);  // Note(D, Duration(16th))
  PlayTone(  622,   24); wait1Msec( 268);  // Note(D#, Duration(Eighth))
  PlayTone(  587,   12); wait1Msec( 134);  // Note(D, Duration(16th))
  PlayTone(  523,   12); wait1Msec( 134);  // Note(C, Duration(16th))
  PlayTone(  523,   12); wait1Msec( 134);  // Note(C, Duration(16th))
  PlayTone(  523,   12); wait1Msec( 134);  // Note(C, Duration(16th))
  PlayTone(  622,   36); wait1Msec( 402);  // Note(D#, Duration(Eighth .))
  PlayTone(  523,   12); wait1Msec( 134);  // Note(C, Duration(16th))
  PlayTone(  523,   12); wait1Msec( 134);  // Note(C, Duration(16th))
  PlayTone(  523,   12); wait1Msec( 134);  // Note(C, Duration(16th))
  PlayTone(  698,   36); wait1Msec( 402);  // Note(F, Duration(Eighth .))
  PlayTone(  523,   12); wait1Msec( 134);  // Note(C, Duration(16th))
  PlayTone(  523,   12); wait1Msec( 134);  // Note(C, Duration(16th))
  PlayTone(  523,   12); wait1Msec( 134);  // Note(C, Duration(16th))
  PlayTone(  739,   12); wait1Msec( 134);  // Note(F#, Duration(16th))
  PlayTone(  698,   12); wait1Msec( 134);  // Note(F, Duration(16th))
  PlayTone(  622,   12); wait1Msec( 134);  // Note(D#, Duration(16th))
  PlayTone(  698,   12); wait1Msec( 134);  // Note(F, Duration(16th))
  PlayTone(  622,   12); wait1Msec( 134);  // Note(D#, Duration(16th))
  PlayTone(  587,   12); wait1Msec( 134);  // Note(D, Duration(16th))
  PlayTone(  622,   12); wait1Msec( 134);  // Note(D#, Duration(16th))
  PlayTone(  587,   12); wait1Msec( 134);  // Note(D, Duration(16th))
  PlayTone(  523,   12); wait1Msec( 134);  // Note(C, Duration(16th))
  return;
}

void Zelda1()
{
  //        125 = Tempo
  //          5 = Default octave
  //    Quarter = Default note length
  //        10% = Break between notes
  //
  PlayTone(  932,   43); wait1Msec( 480);  // Note(A#)
  PlayTone(  698,   65); wait1Msec( 720);  // Note(F, Duration(Quarter .))
  PlayTone(  932,   22); wait1Msec( 240);  // Note(A#, Duration(Eighth))
  PlayTone(  932,   11); wait1Msec( 120);  // Note(A#, Duration(16th))
  PlayTone(  784,   11); wait1Msec( 120);  // Note(C6, Duration(16th))
  PlayTone(  880,   11); wait1Msec( 120);  // Note(D6, Duration(16th))
  PlayTone(  933,   11); wait1Msec( 120);  // Note(D#6, Duration(16th))
  PlayTone( 1047,   86); wait1Msec( 960);  // Note(F6, Duration(Half))
  PlayTone(    0,   22); wait1Msec( 240);  // Note(Rest, Duration(Eighth))
  PlayTone( 1047,   22); wait1Msec( 240);  // Note(F6, Duration(Eighth))
  PlayTone( 1047,   16); wait1Msec( 180);  // Note(F6, Duration(16th .))
  PlayTone( 1109,   11); wait1Msec( 120);  // Note(F#6, Duration(16th))
  PlayTone( 1245,   16); wait1Msec( 180);  // Note(G#6, Duration(16th .))
  PlayTone( 1398,  130); wait1Msec(1440);  // Note(A#6, Duration(Half .))
  PlayTone( 1398,   16); wait1Msec( 180);  // Note(A#6, Duration(16th .))
  PlayTone( 1245,   11); wait1Msec( 120);  // Note(G#6, Duration(16th))
  PlayTone( 1109,   16); wait1Msec( 180);  // Note(F#6, Duration(16th .))
  PlayTone( 1245,   32); wait1Msec( 360);  // Note(G#6, Duration(Eighth .))
  PlayTone( 1109,   16); wait1Msec( 180);  // Note(F#6, Duration(16th .))
  PlayTone( 1047,   86); wait1Msec( 960);  // Note(F6, Duration(Half))
  PlayTone( 1047,   43); wait1Msec( 480);  // Note(F6)
  PlayTone(  933,   22); wait1Msec( 240);  // Note(D#6, Duration(Eighth))
  PlayTone(  933,   11); wait1Msec( 120);  // Note(D#6, Duration(16th))
  PlayTone( 1047,   11); wait1Msec( 120);  // Note(F6, Duration(16th))
  PlayTone( 1109,   86); wait1Msec( 960);  // Note(F#6, Duration(Half))
  PlayTone( 1047,   22); wait1Msec( 240);  // Note(F6, Duration(Eighth))
  PlayTone(  933,   22); wait1Msec( 240);  // Note(D#6, Duration(Eighth))
  PlayTone(  831,   22); wait1Msec( 240);  // Note(C#6, Duration(Eighth))
  PlayTone(  831,   11); wait1Msec( 120);  // Note(C#6, Duration(16th))
  PlayTone(  933,   11); wait1Msec( 120);  // Note(D#6, Duration(16th))
  PlayTone( 1047,   86); wait1Msec( 960);  // Note(F6, Duration(Half))
  PlayTone(  933,   22); wait1Msec( 240);  // Note(D#6, Duration(Eighth))
  PlayTone(  831,   22); wait1Msec( 240);  // Note(C#6, Duration(Eighth))
  PlayTone(  784,   22); wait1Msec( 240);  // Note(C6, Duration(Eighth))
  PlayTone(  784,   11); wait1Msec( 120);  // Note(C6, Duration(16th))
  PlayTone(  880,   11); wait1Msec( 120);  // Note(D6, Duration(16th))
  PlayTone(  988,   86); wait1Msec( 960);  // Note(E6, Duration(Half))
  PlayTone( 1175,   43); wait1Msec( 480);  // Note(G6)
  PlayTone( 1047,   22); wait1Msec( 240);  // Note(F6, Duration(Eighth))
  PlayTone(  698,   11); wait1Msec( 120);  // Note(F, Duration(16th))
  PlayTone(  698,   11); wait1Msec( 120);  // Note(F, Duration(16th))
  PlayTone(  698,   22); wait1Msec( 240);  // Note(F, Duration(Eighth))
  PlayTone(  698,   11); wait1Msec( 120);  // Note(F, Duration(16th))
  PlayTone(  698,   11); wait1Msec( 120);  // Note(F, Duration(16th))
  PlayTone(  698,   22); wait1Msec( 240);  // Note(F, Duration(Eighth))
  PlayTone(  698,   11); wait1Msec( 120);  // Note(F, Duration(16th))
  PlayTone(  698,   11); wait1Msec( 120);  // Note(F, Duration(16th))
  PlayTone(  698,   22); wait1Msec( 240);  // Note(F, Duration(Eighth))
  PlayTone(  698,   22); wait1Msec( 240);  // Note(F, Duration(Eighth))
  PlayTone(  932,   43); wait1Msec( 480);  // Note(A#)
  PlayTone(  698,   65); wait1Msec( 720);  // Note(F, Duration(Quarter .))
  PlayTone(  932,   22); wait1Msec( 240);  // Note(A#, Duration(Eighth))
  PlayTone(  932,   11); wait1Msec( 120);  // Note(A#, Duration(16th))
  PlayTone(  784,   11); wait1Msec( 120);  // Note(C6, Duration(16th))
  PlayTone(  880,   11); wait1Msec( 120);  // Note(D6, Duration(16th))
  PlayTone(  933,   11); wait1Msec( 120);  // Note(D#6, Duration(16th))
  PlayTone( 1047,   86); wait1Msec( 960);  // Note(F6, Duration(Half))
  PlayTone(    0,   22); wait1Msec( 240);  // Note(Rest, Duration(Eighth))
  PlayTone( 1047,   22); wait1Msec( 240);  // Note(F6, Duration(Eighth))
  PlayTone( 1047,   16); wait1Msec( 180);  // Note(F6, Duration(16th .))
  PlayTone( 1109,   11); wait1Msec( 120);  // Note(F#6, Duration(16th))
  PlayTone( 1245,   16); wait1Msec( 180);  // Note(G#6, Duration(16th .))
  PlayTone( 1398,  130); wait1Msec(1440);  // Note(A#6, Duration(Half .))
  PlayTone( 1108,   43); wait1Msec( 480);  // Note(C#7)
  PlayTone( 1046,   43); wait1Msec( 480);  // Note(C7)
  PlayTone( 1320,   86); wait1Msec( 960);  // Note(A6, Duration(Half))
  PlayTone( 1047,   43); wait1Msec( 480);  // Note(F6)
  PlayTone( 1109,  130); wait1Msec(1440);  // Note(F#6, Duration(Half .))
  PlayTone( 1398,   43); wait1Msec( 480);  // Note(A#6)
  PlayTone( 1320,   43); wait1Msec( 480);  // Note(A6)
  PlayTone( 1047,   86); wait1Msec( 960);  // Note(F6, Duration(Half))
  PlayTone( 1047,   43); wait1Msec( 480);  // Note(F6)
  PlayTone( 1109,  130); wait1Msec(1440);  // Note(F#6, Duration(Half .))
  PlayTone( 1398,   43); wait1Msec( 480);  // Note(A#6)
  PlayTone( 1320,   43); wait1Msec( 480);  // Note(A6)
  PlayTone( 1047,   86); wait1Msec( 960);  // Note(F6, Duration(Half))
  PlayTone(  880,   43); wait1Msec( 480);  // Note(D6)
  PlayTone(  933,  130); wait1Msec(1440);  // Note(D#6, Duration(Half .))
  PlayTone( 1109,   43); wait1Msec( 480);  // Note(F#6)
  PlayTone( 1047,   43); wait1Msec( 480);  // Note(F6)
  PlayTone(  831,   86); wait1Msec( 960);  // Note(C#6, Duration(Half))
  PlayTone(  932,   43); wait1Msec( 480);  // Note(A#)
  PlayTone(  784,   43); wait1Msec( 480);  // Note(C6)
  PlayTone(  880,   11); wait1Msec( 120);  // Note(D6, Duration(16th))
  PlayTone(  988,   86); wait1Msec( 960);  // Note(E6, Duration(Half))
  PlayTone( 1175,   43); wait1Msec( 480);  // Note(G6)
  PlayTone( 1047,   22); wait1Msec( 240);  // Note(F6, Duration(Eighth))
  PlayTone(  698,   11); wait1Msec( 120);  // Note(F, Duration(16th))
  PlayTone(  698,   11); wait1Msec( 120);  // Note(F, Duration(16th))
  PlayTone(  698,   22); wait1Msec( 240);  // Note(F, Duration(Eighth))
  PlayTone(  698,   11); wait1Msec( 120);  // Note(F, Duration(16th))
  PlayTone(  698,   11); wait1Msec( 120);  // Note(F, Duration(16th))
  PlayTone(  698,   22); wait1Msec( 240);  // Note(F, Duration(Eighth))
  PlayTone(  698,   11); wait1Msec( 120);  // Note(F, Duration(16th))
  PlayTone(  698,   11); wait1Msec( 120);  // Note(F, Duration(16th))
  PlayTone(  698,   22); wait1Msec( 240);  // Note(F, Duration(Eighth))
  PlayTone(  698,   22); wait1Msec( 240);  // Note(F, Duration(Eighth))
  return;
}

void smb3lvl1()
{
  //         80 = Tempo
  //          5 = Default octave
  //    Quarter = Default note length
  //        10% = Break between notes
  //
  PlayTone(  783,   17); wait1Msec( 188);  // Note(G, Duration(16th))
  PlayTone(  523,    8); wait1Msec(  94);  // Note(C, Duration(32th))
  PlayTone(  783,   25); wait1Msec( 281);  // Note(G, Duration(16th .))
  PlayTone(  880,   17); wait1Msec( 188);  // Note(A, Duration(16th))
  PlayTone(  523,    8); wait1Msec(  94);  // Note(C, Duration(32th))
  PlayTone(  880,   25); wait1Msec( 281);  // Note(A, Duration(16th .))
  PlayTone(  987,   17); wait1Msec( 188);  // Note(B, Duration(16th))
  PlayTone(  523,    8); wait1Msec(  94);  // Note(C, Duration(32th))
  PlayTone(  987,   17); wait1Msec( 188);  // Note(B, Duration(16th))
  PlayTone(  880,   25); wait1Msec( 281);  // Note(A, Duration(16th .))
  PlayTone(  830,    8); wait1Msec(  94);  // Note(G#, Duration(32th))
  PlayTone(  880,   25); wait1Msec( 281);  // Note(A, Duration(16th .))
  PlayTone(  783,   17); wait1Msec( 188);  // Note(G, Duration(16th))
  PlayTone(  523,    8); wait1Msec(  94);  // Note(C, Duration(32th))
  PlayTone(  783,   25); wait1Msec( 281);  // Note(G, Duration(16th .))
  PlayTone(  880,   17); wait1Msec( 188);  // Note(A, Duration(16th))
  PlayTone(  523,    8); wait1Msec(  94);  // Note(C, Duration(32th))
  PlayTone(  880,   17); wait1Msec( 188);  // Note(A, Duration(16th))
  PlayTone(  987,  101); wait1Msec(1125);  // Note(B, Duration(Quarter .))
  PlayTone(    0,    8); wait1Msec(  94);  // Note(Rest, Duration(32th))
  PlayTone(  784,   17); wait1Msec( 188);  // Note(C6, Duration(16th))
  PlayTone(  698,    8); wait1Msec(  94);  // Note(F, Duration(32th))
  PlayTone(  784,   25); wait1Msec( 281);  // Note(C6, Duration(16th .))
  PlayTone(  880,   17); wait1Msec( 188);  // Note(D6, Duration(16th))
  PlayTone(  698,    8); wait1Msec(  94);  // Note(F, Duration(32th))
  PlayTone(  880,   25); wait1Msec( 281);  // Note(D6, Duration(16th .))
  PlayTone(  988,   17); wait1Msec( 188);  // Note(E6, Duration(16th))
  PlayTone(  698,    8); wait1Msec(  94);  // Note(F, Duration(32th))
  PlayTone(  988,   17); wait1Msec( 188);  // Note(E6, Duration(16th))
  PlayTone(  880,   25); wait1Msec( 281);  // Note(D6, Duration(16th .))
  PlayTone(  831,    8); wait1Msec(  94);  // Note(C#6, Duration(32th))
  PlayTone(  880,   25); wait1Msec( 281);  // Note(D6, Duration(16th .))
  PlayTone(  784,   17); wait1Msec( 188);  // Note(C6, Duration(16th))
  PlayTone(  698,    8); wait1Msec(  94);  // Note(F, Duration(32th))
  PlayTone(  784,   25); wait1Msec( 281);  // Note(C6, Duration(16th .))
  PlayTone(  880,   17); wait1Msec( 188);  // Note(D6, Duration(16th))
  PlayTone(  698,    8); wait1Msec(  94);  // Note(F, Duration(32th))
  PlayTone(  880,   17); wait1Msec( 188);  // Note(D6, Duration(16th))
  PlayTone(  988,  101); wait1Msec(1125);  // Note(E6, Duration(Quarter .))
  PlayTone(    0,    8); wait1Msec(  94);  // Note(Rest, Duration(32th))
  PlayTone(  783,   17); wait1Msec( 188);  // Note(G, Duration(16th))
  PlayTone(  523,    8); wait1Msec(  94);  // Note(C, Duration(32th))
  PlayTone(  783,   25); wait1Msec( 281);  // Note(G, Duration(16th .))
  PlayTone(  880,   17); wait1Msec( 188);  // Note(A, Duration(16th))
  PlayTone(  523,    8); wait1Msec(  94);  // Note(C, Duration(32th))
  PlayTone(  880,   25); wait1Msec( 281);  // Note(A, Duration(16th .))
  PlayTone(  987,   17); wait1Msec( 188);  // Note(B, Duration(16th))
  PlayTone(  523,    8); wait1Msec(  94);  // Note(C, Duration(32th))
  PlayTone(  987,   17); wait1Msec( 188);  // Note(B, Duration(16th))
  PlayTone(  880,   25); wait1Msec( 281);  // Note(A, Duration(16th .))
  PlayTone(  830,    8); wait1Msec(  94);  // Note(G#, Duration(32th))
  PlayTone(  880,   25); wait1Msec( 281);  // Note(A, Duration(16th .))
  PlayTone(  784,   17); wait1Msec( 188);  // Note(C6, Duration(16th))
  PlayTone(  784,   51); wait1Msec( 563);  // Note(C6, Duration(Eighth .))
  PlayTone(    0,    8); wait1Msec(  94);  // Note(Rest, Duration(32th))
  PlayTone(  784,   17); wait1Msec( 188);  // Note(C6, Duration(16th))
  PlayTone(  784,  101); wait1Msec(1125);  // Note(C6, Duration(Quarter .))
  return;
}

void dkcjung()
{
  //        140 = Tempo
  //          5 = Default octave
  //    Quarter = Default note length
  //        10% = Break between notes
  //
  PlayTone(  880,   19); wait1Msec( 214);  // Note(A, Duration(Eighth))
  PlayTone(  784,   10); wait1Msec( 107);  // Note(C6, Duration(16th))
  PlayTone(  933,   19); wait1Msec( 214);  // Note(D#6, Duration(Eighth))
  PlayTone(  988,   19); wait1Msec( 214);  // Note(E6, Duration(Eighth))
  PlayTone(    0,   10); wait1Msec( 107);  // Note(Rest, Duration(16th))
  PlayTone(  830,   10); wait1Msec( 107);  // Note(G#, Duration(16th))
  PlayTone(  880,   19); wait1Msec( 214);  // Note(A, Duration(Eighth))
  PlayTone(  784,   10); wait1Msec( 107);  // Note(C6, Duration(16th))
  PlayTone(  933,   19); wait1Msec( 214);  // Note(D#6, Duration(Eighth))
  PlayTone(  988,   19); wait1Msec( 214);  // Note(E6, Duration(Eighth))
  PlayTone(    0,   77); wait1Msec( 857);  // Note(Rest, Duration(Half))
  PlayTone(  880,   19); wait1Msec( 214);  // Note(A, Duration(Eighth))
  PlayTone(  784,   10); wait1Msec( 107);  // Note(C6, Duration(16th))
  PlayTone(  933,   19); wait1Msec( 214);  // Note(D#6, Duration(Eighth))
  PlayTone(  988,   10); wait1Msec( 107);  // Note(E6, Duration(16th))
  PlayTone(  880,   19); wait1Msec( 214);  // Note(D6, Duration(Eighth))
  PlayTone(  784,   10); wait1Msec( 107);  // Note(C6, Duration(16th))
  PlayTone(  880,   29); wait1Msec( 321);  // Note(D6, Duration(Eighth .))
  PlayTone(    0,   77); wait1Msec( 857);  // Note(Rest, Duration(Half))
  PlayTone(    0,   39); wait1Msec( 429);  // Note(Rest)
  PlayTone(  830,   19); wait1Msec( 214);  // Note(G#, Duration(Eighth))
  PlayTone(  880,   10); wait1Msec( 107);  // Note(A, Duration(16th))
  PlayTone(  987,   19); wait1Msec( 214);  // Note(B, Duration(Eighth))
  PlayTone(  880,   19); wait1Msec( 214);  // Note(D6, Duration(Eighth))
  PlayTone(    0,   10); wait1Msec( 107);  // Note(Rest, Duration(16th))
  PlayTone(  659,   10); wait1Msec( 107);  // Note(E, Duration(16th))
  PlayTone(  830,   19); wait1Msec( 214);  // Note(G#, Duration(Eighth))
  PlayTone(  880,   10); wait1Msec( 107);  // Note(A, Duration(16th))
  PlayTone(  987,   19); wait1Msec( 214);  // Note(B, Duration(Eighth))
  PlayTone(  880,   19); wait1Msec( 214);  // Note(D6, Duration(Eighth))
  PlayTone(    0,   39); wait1Msec( 429);  // Note(Rest)
  PlayTone(  933,   19); wait1Msec( 214);  // Note(D#6, Duration(Eighth))
  PlayTone(  988,   10); wait1Msec( 107);  // Note(E6, Duration(16th))
  PlayTone(  933,   19); wait1Msec( 214);  // Note(D#6, Duration(Eighth))
  PlayTone(  988,   10); wait1Msec( 107);  // Note(E6, Duration(16th))
  PlayTone(  933,   19); wait1Msec( 214);  // Note(D#6, Duration(Eighth))
  PlayTone(  880,   10); wait1Msec( 107);  // Note(D6, Duration(16th))
  PlayTone(  784,   19); wait1Msec( 214);  // Note(C6, Duration(Eighth))
  PlayTone(  987,   10); wait1Msec( 107);  // Note(B, Duration(16th))
  PlayTone(  784,   29); wait1Msec( 321);  // Note(C6, Duration(Eighth .))
  return;
}

void Guile()
{
  //        125 = Tempo
  //          5 = Default octave
  //    Quarter = Default note length
  //        10% = Break between notes
  //
  PlayTone(  831,   22); wait1Msec( 240);  // Note(C#6, Duration(Eighth))
  PlayTone(  831,   11); wait1Msec( 120);  // Note(C#6, Duration(16th))
  PlayTone(  987,   22); wait1Msec( 240);  // Note(B, Duration(Eighth))
  PlayTone(  987,   11); wait1Msec( 120);  // Note(B, Duration(16th))
  PlayTone(  831,   86); wait1Msec( 960);  // Note(C#6, Duration(Half))
  PlayTone(  831,   11); wait1Msec( 120);  // Note(C#6, Duration(16th))
  PlayTone(  987,   22); wait1Msec( 240);  // Note(B, Duration(Eighth))
  PlayTone(  831,   22); wait1Msec( 240);  // Note(C#6, Duration(Eighth))
  PlayTone(  831,   11); wait1Msec( 120);  // Note(C#6, Duration(16th))
  PlayTone(  987,   22); wait1Msec( 240);  // Note(B, Duration(Eighth))
  PlayTone(  987,   11); wait1Msec( 120);  // Note(B, Duration(16th))
  PlayTone(  831,   86); wait1Msec( 960);  // Note(C#6, Duration(Half))
  PlayTone(  831,   11); wait1Msec( 120);  // Note(C#6, Duration(16th))
  PlayTone(  987,   22); wait1Msec( 240);  // Note(B, Duration(Eighth))
  PlayTone(  831,   11); wait1Msec( 120);  // Note(C#6, Duration(16th))
  PlayTone(  987,   22); wait1Msec( 240);  // Note(B, Duration(Eighth))
  PlayTone(  831,   22); wait1Msec( 240);  // Note(C#6, Duration(Eighth))
  PlayTone(  987,   22); wait1Msec( 240);  // Note(B, Duration(Eighth))
  PlayTone( 1109,   22); wait1Msec( 240);  // Note(F#6, Duration(Eighth))
  PlayTone( 1109,   11); wait1Msec( 120);  // Note(F#6, Duration(16th))
  PlayTone(  988,   22); wait1Msec( 240);  // Note(E6, Duration(Eighth))
  PlayTone(  933,   22); wait1Msec( 240);  // Note(D#6, Duration(Eighth))
  PlayTone(  987,   22); wait1Msec( 240);  // Note(B, Duration(Eighth))
  return;
}

void korobyeyniki()
{
  //        160 = Tempo
  //          5 = Default octave
  //    Quarter = Default note length
  //        10% = Break between notes
  //
  PlayTone(  988,   34); wait1Msec( 375);  // Note(E6)
  PlayTone(  987,   17); wait1Msec( 188);  // Note(B, Duration(Eighth))
  PlayTone(  784,   17); wait1Msec( 188);  // Note(C6, Duration(Eighth))
  PlayTone(  880,   17); wait1Msec( 188);  // Note(D6, Duration(Eighth))
  PlayTone(  988,    8); wait1Msec(  94);  // Note(E6, Duration(16th))
  PlayTone(  880,    8); wait1Msec(  94);  // Note(D6, Duration(16th))
  PlayTone(  784,   17); wait1Msec( 188);  // Note(C6, Duration(Eighth))
  PlayTone(  987,   17); wait1Msec( 188);  // Note(B, Duration(Eighth))
  PlayTone(  880,   34); wait1Msec( 375);  // Note(A)
  PlayTone(  880,   17); wait1Msec( 188);  // Note(A, Duration(Eighth))
  PlayTone(  784,   17); wait1Msec( 188);  // Note(C6, Duration(Eighth))
  PlayTone(  988,   34); wait1Msec( 375);  // Note(E6)
  PlayTone(  880,   17); wait1Msec( 188);  // Note(D6, Duration(Eighth))
  PlayTone(  784,   17); wait1Msec( 188);  // Note(C6, Duration(Eighth))
  PlayTone(  987,   34); wait1Msec( 375);  // Note(B)
  PlayTone(  987,   17); wait1Msec( 188);  // Note(B, Duration(Eighth))
  PlayTone(  784,   17); wait1Msec( 188);  // Note(C6, Duration(Eighth))
  PlayTone(  880,   34); wait1Msec( 375);  // Note(D6)
  PlayTone(  988,   34); wait1Msec( 375);  // Note(E6)
  PlayTone(  784,   34); wait1Msec( 375);  // Note(C6)
  PlayTone(  880,   34); wait1Msec( 375);  // Note(A)
  PlayTone(  880,   68); wait1Msec( 750);  // Note(A, Duration(Half))
  PlayTone(    0,   17); wait1Msec( 188);  // Note(Rest, Duration(Eighth))
  PlayTone(  880,   34); wait1Msec( 375);  // Note(D6)
  PlayTone( 1047,   17); wait1Msec( 188);  // Note(F6, Duration(Eighth))
  PlayTone( 1320,   34); wait1Msec( 375);  // Note(A6)
  PlayTone( 1175,   17); wait1Msec( 188);  // Note(G6, Duration(Eighth))
  PlayTone( 1047,   17); wait1Msec( 188);  // Note(F6, Duration(Eighth))
  PlayTone(  988,   34); wait1Msec( 375);  // Note(E6)
  PlayTone(  988,   17); wait1Msec( 188);  // Note(E6, Duration(Eighth))
  PlayTone(  784,   17); wait1Msec( 188);  // Note(C6, Duration(Eighth))
  PlayTone(  988,   34); wait1Msec( 375);  // Note(E6)
  PlayTone(  880,   17); wait1Msec( 188);  // Note(D6, Duration(Eighth))
  PlayTone(  784,   17); wait1Msec( 188);  // Note(C6, Duration(Eighth))
  PlayTone(  987,   34); wait1Msec( 375);  // Note(B)
  PlayTone(  987,   17); wait1Msec( 188);  // Note(B, Duration(Eighth))
  PlayTone(  784,   17); wait1Msec( 188);  // Note(C6, Duration(Eighth))
  PlayTone(  880,   34); wait1Msec( 375);  // Note(D6)
  PlayTone(  988,   34); wait1Msec( 375);  // Note(E6)
  PlayTone(  784,   34); wait1Msec( 375);  // Note(C6)
  PlayTone(  880,   34); wait1Msec( 375);  // Note(A)
  PlayTone(  880,   34); wait1Msec( 375);  // Note(A)
  return;
}

task music () {
	count = 1;
	int ignore = SensorValue[sonar];
	while (true) {
		if(bSoundQueueAvailable && SensorValue[sonar] < ignore) // if there is still space in the Sound Queue:
		{
			int tone = abs(SensorValue[sonar])*pitch;
			playImmediateTone(tone, 50);  // play tone according to sensor readings
			if (recordS == "startReady") {
				rec[(count)][(rData)] = tone;
				recBpm[(count)][(rData)] = bpm;
				count = count + 1;
			}
			wait1Msec(((60000-(bpm*50))/bpm));
		}
	}
}

string snd;
task music2 () {
	count = 1;
	int ignore = SensorValue[sonar];
	while (true) {
		if(bSoundQueueAvailable && SensorValue[sonar] < ignore) // if there is still space in the Sound Queue:
		{
			if (SensorValue[sonar] <= 4) {
				snd = "pulse1.wav";
			} else if (SensorValue[sonar] <= 8) {
				snd = "pulse2.wav";
			} else if (SensorValue[sonar] <= 12) {
				snd = "pulse3.wav";
			} else if (SensorValue[sonar] <= 16) {
				snd = "pulse4.wav";
			} else if (SensorValue[sonar] <= 20) {
				snd = "pulse5.wav";
			} else if (SensorValue[sonar] <= 24) {
				snd = "pulse6.wav";
			} else if (SensorValue[sonar] <= 28) {
				snd = "pulse7.wav";
			} else if (SensorValue[sonar] <= 32) {
				snd = "pulse8.wav";
			} else if (SensorValue[sonar] <= 36) {
				snd = "pulse9.wav";
			} else {
				snd = "pulse10.wav";
			}
			playSoundFile(snd);
			wait1Msec(50);
			if (recordS == "startReady") {
				rec2[(count)][(rData)] = snd;
				rec[(count)][(rData)] = -1;
				recBpm[(count)][(rData)] = bpm;
				count = count + 1;
			}
			wait1Msec(((60000-(bpm*50))/bpm));
		}
	}
}

task debug () {
	clearLCDLine(0);
	clearLCDLine(1);
	while (true) {
		bLCDBacklight = true;									// Turn on LCD Backlight
		displayLCDPos(0,0);
		string display1;
		sprintf(display1, "BPM:%3d  STR:%3d", bpm, spm);
		displayNextLCDString(display1);
		displayLCDPos(1,0);
		string display2;
		sprintf(display2, "PITCH: %3d", pitch);
		displayNextLCDString(display2);
	}
}

task bpmConfig () {
	clearLCDLine(0);
	clearLCDLine(1);
	while (true) {
		bLCDBacklight = true;									// Turn on LCD Backlight
		displayLCDPos(0,0);
		string display1;
		sprintf(display1, " CONFIGURE  BPM ");
		displayNextLCDString(display1);
		displayLCDPos(1,0);
		string display2;
		sprintf(display2, "    BPM: %3d    ", bpm);
		displayNextLCDString(display2);
	}
}

task spmConfig () {
	clearLCDLine(0);
	clearLCDLine(1);
	while (true) {
		bLCDBacklight = true;									// Turn on LCD Backlight
		displayLCDPos(0,0);
		string display1;
		sprintf(display1, "CONFIGURE STROBE");
		displayNextLCDString(display1);
		displayLCDPos(1,0);
		string display2;
		sprintf(display2, "STROBE RATE: %3d", spm);
		displayNextLCDString(display2);
	}
}

task pitchConfig () {
	clearLCDLine(0);
	clearLCDLine(1);
	while (true) {
		bLCDBacklight = true;									// Turn on LCD Backlight
		displayLCDPos(0,0);
		string display1;
		sprintf(display1, "CONFIGURE  PITCH");
		displayNextLCDString(display1);
		displayLCDPos(1,0);
		string display2;
		sprintf(display2, "   PITCH:  %2d   ", pitch);
		displayNextLCDString(display2);
	}
}

task playr () {
	clearLCDLine(0);
	clearLCDLine(1);
	while (true) {
		bLCDBacklight = true;									// Turn on LCD Backlight
		displayLCDPos(0,0);
		string display1;
		sprintf(display1, "CURRENT RECORD  ");
		displayNextLCDString(display1);
		displayLCDPos(1,0);
		string display2;
		sprintf(display2, "RECORD : %2d      ", curData);
		displayNextLCDString(display2);
	}
}

string fader = "rising";
task strobe() {
	while (true) {
		if (fader == "rising") {
			if (motor[flashlight] < 127) {
				motor[flashlight] = motor[flashlight] + 1;
				wait1Msec(60000/(spm*254));
			} else {
				fader = "fading";
			}
		}	else {
			if (motor[flashlight] > 0) {
				motor[flashlight] = motor[flashlight] - 1;
				wait1Msec(60000/(spm*254));
			} else {
				fader = "rising";
			}
		}
	}
}

void tank() {
	motor[FL] = vexRT[Ch3];
	motor[BL] = vexRT[Ch3];
	motor[FR] = vexRT[Ch2];
	motor[BR] = vexRT[Ch2];
}

void tankMotion() {
	if (abs(vexRT[AccelX]) > abs(vexRT[AccelY])) {
		motor[BR] = (-(vexRT[AccelX])) / 2;
		motor[FR] = (-(vexRT[AccelX])) / 2;
		motor[BL] = (vexRT[AccelX]) / 2;
		motor[FL] = (vexRT[AccelX]) / 2;
		} else if (abs(vexRT[AccelY]) >= abs(vexRT[AccelX])) {
		motor[BR] = (-(vexRT[AccelY]));
		motor[FR] = (-(vexRT[AccelY]));
		motor[BL] = (-(vexRT[AccelY]));
		motor[FL] = (-(vexRT[AccelY]));
	}
}

int X2 = 0, Y1 = 0, X1 = 0, threshold = 15;
void tankMecanum() {
	//Create "deadzone" for Y1/Ch3
	if (abs(vexRT[Ch3]) > threshold) {
		Y1 = vexRT[Ch3];
		} else {
		Y1 = 0;
	}
	//Create "deadzone" for X1/Ch4
	if (abs(vexRT[Ch4]) > threshold) {
		X1 = vexRT[Ch4];
		} else {
		X1 = 0;
	}
	//Create "deadzone" for X2/Ch1
	if (abs(vexRT[Ch1]) > threshold) {
		X2 = vexRT[Ch1];
		} else {
		X2 = 0;
	}
	//Remote Control Commands
	motor[FR] = Y1 - X2 - X1;
	motor[BR] =  Y1 - X2 + X1;
	motor[FL] = Y1 + X2 + X1;
	motor[BL] =  Y1 + X2 - X1;
}

void tankMotionMecanum() {
	if (abs(vexRT[AccelY]) > threshold) {
		Y1 = -(vexRT[AccelY]);
		} else {
		Y1 = 0;
	}
	//Create "deadzone" for X1/Ch4
	if ((abs(vexRT[AccelX]) > threshold) && (vexRT[Btn5D] == 0)) {
		X1 = (vexRT[AccelX]);
		} else {
		X1 = 0;
	}
	//Create "deadzone" for X2/Ch1
	if ((abs(vexRT[AccelX]) > threshold) && (vexRT[Btn5D] == 1)) {
		X2 = (vexRT[AccelX])/2;
		} else {
		X2 = 0;
	}
	//Remote Control Commands
	motor[FR] = Y1 - X2 - X1;
	motor[BR] =  Y1 - X2 + X1;
	motor[FL] = Y1 + X2 + X1;
	motor[BL] =  Y1 + X2 - X1;
}

string playMode;

task playback() {
	clearLCDLine(0);
	clearLCDLine(1);
	count = 1;
	curData = rData;
	startTask(playr);
	while (true) {
		if (nLCDButtons == 2 || playMode == "play") {
			if (rec[(count)][(curData)] != 0) {
				if (rec[(count)][(curData)] == -1) {
					playSoundFile(rec2[(count)][(curData)]);
					wait1Msec(50);
				} else {
					playImmediateTone(rec[(count)][(curData)], 50);  // play tone according to sensor readings
				}
				wait1Msec(((60000-(50*bpm))/recBpm[(count)][(curData)]));
				count = count + 1;
			}	else {
				count = 1;
			}
			playMode = "play";
		}
		if (nLCDButtons == 7) {
			playMode = "stop";
		}
		if (nLCDButtons == 1 && curData > 1) {
			curData = curData - 1;
			count = 1;
			wait1Msec(CHANGE);
		}
		if (nLCDButtons == 4 && curData < rData) {
			curData = curData + 1;
			count = 1;
			wait1Msec(CHANGE);
		}
	}
}

void record()
{
	if (vexRT[Btn6U] == 1) {
		if (recordS == "ready") {
			recordS = "start";
			rData = rData + 1;
			mode = "alert";
			stopTask(bpmConfig);
			stopTask(spmConfig);
			stopTask(pitchConfig);
			stopTask(debug);
			d1 = "RECORDING       ";
			d2 = "STARTED         ";
			message();
			wait1Msec(1000);
			mode = prevMode;
			//for (int i = 0; i < ARRAYSIZE(rec); i++) {
			//	rec[i] = 0;
			//	recBpm[i] = 0;
			//}
		}	else if (recordS == "startReady") {
			recordS = "finish";
			stopTask(music);
			stopTask(music2);
			mode = "alert";
			stopTask(bpmConfig);
			stopTask(spmConfig);
			stopTask(pitchConfig);
			stopTask(debug);
			startTask(playback);
		} else if (recordS == "quit") {
			recordS = "quitReady";
			startTask(music);
			stopTask(playback);
			stopTask(playr);
			mode = prevMode;
		}
	}	else {
		if (recordS == "start") {
			recordS = "startReady";
		}	else if (recordS == "finish") {
			recordS = "quit";
		} else if (recordS == "quitReady") {
			recordS = "ready";
		}
	}
}

void songPly() {
	if (vexRT[Btn8R] == 1) {
		  mode = "alert";
			stopTask(bpmConfig);
			stopTask(spmConfig);
			stopTask(pitchConfig);
			stopTask(debug);
			d1 = "SUPER MARIO BROS";
			d2 = "UNDERGROUND THME";
			message();
			smb_under();
			mode = prevMode;
	}
	if (vexRT[Btn8D] == 1) {
		  mode = "alert";
			stopTask(bpmConfig);
			stopTask(spmConfig);
			stopTask(pitchConfig);
			stopTask(debug);
			d1 = "SUPER MARIO WRLD";
			d2 = "MAIN THEME      ";
			message();
			smw_title();
			mode = prevMode;
	}
  if (vexRT[Btn8L] == 1) {
		  mode = "alert";
			stopTask(bpmConfig);
			stopTask(spmConfig);
			stopTask(pitchConfig);
			stopTask(debug);
			d1 = "SUPER MARIO BR 3";
			d2 = "MAIN THEME      ";
			message();
			smb3lvl1();
			mode = prevMode;
	}
	if (vexRT[Btn8U] == 1) {
		  mode = "alert";
			stopTask(bpmConfig);
			stopTask(spmConfig);
			stopTask(pitchConfig);
			stopTask(debug);
			d1 = "LEGEND OF ZELDA ";
			d2 = "MAIN THEME      ";
			message();
		  Zelda1();
			mode = prevMode;
	}
	if (vexRT[Btn7U] == 1) {
		  mode = "alert";
			stopTask(bpmConfig);
			stopTask(spmConfig);
			stopTask(pitchConfig);
			stopTask(debug);
			d1 = "FINAL FANTASY  7";
			d2 = "BOSS THEME      ";
			message();
		  ffvii_boss();
			mode = prevMode;
	}
	if (vexRT[Btn7R] == 1) {
		  mode = "alert";
			stopTask(bpmConfig);
			stopTask(spmConfig);
			stopTask(pitchConfig);
			stopTask(debug);
			d1 = "DONKEY KONG CTRY";
			d2 = "JUNGLE THEME    ";
			message();
		  dkcjung();
			mode = prevMode;
	}
  if (vexRT[Btn7D] == 1) {
		  mode = "alert";
			stopTask(bpmConfig);
			stopTask(spmConfig);
			stopTask(pitchConfig);
			stopTask(debug);
			d1 = "STREET FIGHTER 2";
			d2 = "GUILE'S THEME   ";
			message();
		  Guile();
			mode = prevMode;
	}
	  if (vexRT[Btn7L] == 1) {
		  mode = "alert";
			stopTask(bpmConfig);
			stopTask(spmConfig);
			stopTask(pitchConfig);
			stopTask(debug);
			d1 = "TETRIS          ";
			d2 = "THEME A         ";
			message();
		  korobyeyniki();
			mode = prevMode;
	}
}

task main()
{
	while (true) {
		if (power == "on") {
			record();
			songPly();
			tank();
			if (vexRT[Btn5D] == 1) {
				stopTask(music2);
				startTask(music);
			}
			if (vexRT[Btn6D] == 1) {
				stopTask(music);
				startTask(music2);
			}
			if (mode == "alert") {
			}
			else if (mode == "debug") {
				stopTask(bpmConfig);
				stopTask(spmConfig);
				stopTask(pitchConfig);
				startTask(debug);
				mode = "";
				prevMode = "debug";
				wait1Msec(1000);
			}
			else if (nLCDButtons == 1 || mode == "bpm") {
				mode = "bpm";
				prevMode = "bpm";
				stopTask(debug);
				startTask(bpmConfig);
				wait1Msec(1000);
				while (mode == "bpm") {
					wait1Msec(CHANGE);
					if (nLCDButtons == 1) {
						if (bpm > 1) {
							bpm = bpm - 1;
						}
					}
					else if (nLCDButtons == 4) {
						bpm = bpm + 1;
					}
					else if (nLCDButtons == 2) {
						mode = "debug";
						prevMode = "debug";
					}
				}
			}
			else if (nLCDButtons == 2 || mode == "spm") {
				mode = "spm";
				prevMode = "spm";
				stopTask(debug);
				startTask(spmConfig);
				wait1Msec(1000);
				while (mode == "spm") {
					wait1Msec(CHANGE);
					if (nLCDButtons == 1) {
						if (spm > 1) {
							spm = spm - 1;
						}
					}
					else if (nLCDButtons == 4) {
						spm = spm + 1;
					}
					else if (nLCDButtons == 2) {
						mode = "debug";
						prevMode = "debug";
					}
				}
			}
			else if (nLCDButtons == 4 || mode == "pitch") {
				mode = "pitch";
				prevMode = "pitch";
				stopTask(debug);
				startTask(pitchConfig);
				wait1Msec(1000);
				while (mode == "pitch") {
					wait1Msec(CHANGE);
					if (nLCDButtons == 1) {
						if (pitch > 1) {
							pitch = pitch - 1;
						}
					}
					else if (nLCDButtons == 4) {
						pitch = pitch + 1;
					}
					else if (nLCDButtons == 2) {
						mode = "debug";
						prevMode = "debug";
					}
				}
			}
			if (SensorValue[line] < 2500) {
				stopTask(debug);
				stopTask(strobe);
				stopTask(music);
				stopTask(music2);
				stopTask(playback);
				stopTask(bpmConfig);
				stopTask(spmConfig);
				stopTask(pitchConfig);
				motor[flashlight] = 0;
				bLCDBacklight = false;
				clearLCDLine(0);
				clearLCDLine(1);
				power = "off";
				wait1Msec(1000);
			}
		}
		else if (power == "off") {
			if (SensorValue[line] < 2500) {
				power = "on";
				wait1Msec(1000);
				startTask(strobe);
				startTask(music);
				mode = "debug";
				prevMode = "debug";
			}
		}
	}
}
