#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    gyro,           sensorGyro)
#pragma config(Sensor, in2,    Xaccel,         sensorAccelerometer)
#pragma config(Sensor, in3,    Yaccel,         sensorAccelerometer)
#pragma config(Sensor, in4,    Zaccel,         sensorAccelerometer)
#pragma config(Sensor, in6,    motion,         sensorAnalog)
#pragma config(Sensor, in7,    skills,         sensorAnalog)
#pragma config(Sensor, in8,    colorChoice,    sensorAnalog)
#pragma config(Sensor, dgtl1,  sonarY,         sensorSONAR_cm)
#pragma config(Sensor, dgtl3,  sonarX,         sensorSONAR_cm)
#pragma config(Sensor, dgtl5,  detector,       sensorTouch)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           startIntake,   tmotorVex269_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           FR,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           BR,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           shooter1,      tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_1)
#pragma config(Motor,  port5,           shooter2,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           shooter3,      tmotorVex393_MC29, openLoop, encoderPort, I2C_2)
#pragma config(Motor,  port7,           shooter4,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           FL,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           BL,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          intake,        tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

//Variables in use during competition
int DELAY_TIME = 100; //Time between detection of ball and shoot
int TIMER = 0;
bool LOCK = false;
bool pressed = false;
int fired = 0;
bool sensed = false;
bool soundPlay = false;
int FIREDVAR = 30; //30

//Speed calculator variables
float ANGLE = 51.65725;
float DIMENSION = 365.76;
float DIMENSIONEXTRA = 63.20049;
float RADIUS = 5.08;
int COLOR;
int SHOOTSPEED = 100;
int NETSPEED = 95; //Skills speed
int COOLSPEED = 90; //Cooldown speed
//todo make net speed for auto skills

//POSITION CALCULATOR
//Have sonar on each side of robot, consistently measure angle
//Use angle and sonar to angle robot to 0 deg, use sonar for position
//Have preset net position
//Use formulas to find angle and turn
//Use formulas to find distance
//Use kinematic equations to calculate velocity

/*CONTROLLER GUIDE
Need to map launcher, intake
8* buttons will move to player 2 at some point
5D Motion turning 								 6D Intake
5U Confirm launch									 6U Force launch
7U Unlock									 8U No
7L Lock 7R DLock 					8L	Other 8R Button
7D Lift	^					  ^			 8D Sensors
Ch3 Left			|
<Ch4-FL>		<----Ch1>
|					 Ch2 Right
V					  V
*/

//Update task keeps track of time in match on cortex
task update () {
	while (true) {
		wait1Msec(1000);
		TIMER = TIMER + 1;
	}
}

task ffvii_boss()
{
	//        112 = Tempo
	//          5 = Default octave
	//    Quarter = Default note length
	//        10% = Break between notes
	//
	PlayTone(  440,   12); wait1Msec( 134);  // Note(A4, Duration(16th))
	PlayTone(  440,   12); wait1Msec( 134);  // Note(A4, Duration(16th))
	PlayTone(  440,   12); wait1Msec( 134);  // Note(A4, Duration(16th))
	PlayTone(  523,   36); wait1Msec( 402);  // Note(C, Duration(Eighth .))
	PlayTone(  440,   12); wait1Msec( 134);  // Note(A4, Duration(16th))
	PlayTone(  440,   12); wait1Msec( 134);  // Note(A4, Duration(16th))
	PlayTone(  440,   12); wait1Msec( 134);  // Note(A4, Duration(16th))
	PlayTone(  587,   36); wait1Msec( 402);  // Note(D, Duration(Eighth .))
	PlayTone(  440,   12); wait1Msec( 134);  // Note(A4, Duration(16th))
	PlayTone(  440,   12); wait1Msec( 134);  // Note(A4, Duration(16th))
	PlayTone(  440,   12); wait1Msec( 134);  // Note(A4, Duration(16th))
	PlayTone(  622,   12); wait1Msec( 134);  // Note(D#, Duration(16th))
	PlayTone(  587,   12); wait1Msec( 134);  // Note(D, Duration(16th))
	PlayTone(  523,   12); wait1Msec( 134);  // Note(C, Duration(16th))
	PlayTone(  587,   12); wait1Msec( 134);  // Note(D, Duration(16th))
	PlayTone(  523,   12); wait1Msec( 134);  // Note(C, Duration(16th))
	PlayTone(  493,   12); wait1Msec( 134);  // Note(B4, Duration(16th))
	PlayTone(  523,   24); wait1Msec( 268);  // Note(C, Duration(Eighth))
	PlayTone(  493,   12); wait1Msec( 134);  // Note(B4, Duration(16th))
	PlayTone(  440,   12); wait1Msec( 134);  // Note(A4, Duration(16th))
	PlayTone(  440,   12); wait1Msec( 134);  // Note(A4, Duration(16th))
	PlayTone(  440,   12); wait1Msec( 134);  // Note(A4, Duration(16th))
	PlayTone(  523,   36); wait1Msec( 402);  // Note(C, Duration(Eighth .))
	PlayTone(  440,   12); wait1Msec( 134);  // Note(A4, Duration(16th))
	PlayTone(  440,   12); wait1Msec( 134);  // Note(A4, Duration(16th))
	PlayTone(  440,   12); wait1Msec( 134);  // Note(A4, Duration(16th))
	PlayTone(  587,   36); wait1Msec( 402);  // Note(D, Duration(Eighth .))
	PlayTone(  440,   12); wait1Msec( 134);  // Note(A4, Duration(16th))
	PlayTone(  440,   12); wait1Msec( 134);  // Note(A4, Duration(16th))
	PlayTone(  440,   12); wait1Msec( 134);  // Note(A4, Duration(16th))
	PlayTone(  622,   12); wait1Msec( 134);  // Note(D#, Duration(16th))
	PlayTone(  587,   12); wait1Msec( 134);  // Note(D, Duration(16th))
	PlayTone(  523,   12); wait1Msec( 134);  // Note(C, Duration(16th))
	PlayTone(  587,   12); wait1Msec( 134);  // Note(D, Duration(16th))
	PlayTone(  523,   12); wait1Msec( 134);  // Note(C, Duration(16th))
	PlayTone(  493,   12); wait1Msec( 134);  // Note(B4, Duration(16th))
	PlayTone(  523,   24); wait1Msec( 268);  // Note(C, Duration(Eighth))
	PlayTone(  493,   12); wait1Msec( 134);  // Note(B4, Duration(16th))
	PlayTone(  523,   12); wait1Msec( 134);  // Note(C, Duration(16th))
	PlayTone(  523,   12); wait1Msec( 134);  // Note(C, Duration(16th))
	PlayTone(  523,   12); wait1Msec( 134);  // Note(C, Duration(16th))
	PlayTone(  622,   36); wait1Msec( 402);  // Note(D#, Duration(Eighth .))
	PlayTone(  523,   12); wait1Msec( 134);  // Note(C, Duration(16th))
	PlayTone(  523,   12); wait1Msec( 134);  // Note(C, Duration(16th))
	PlayTone(  523,   12); wait1Msec( 134);  // Note(C, Duration(16th))
	PlayTone(  698,   36); wait1Msec( 402);  // Note(F, Duration(Eighth .))
	PlayTone(  523,   12); wait1Msec( 134);  // Note(C, Duration(16th))
	PlayTone(  523,   12); wait1Msec( 134);  // Note(C, Duration(16th))
	PlayTone(  523,   12); wait1Msec( 134);  // Note(C, Duration(16th))
	PlayTone(  739,   12); wait1Msec( 134);  // Note(F#, Duration(16th))
	PlayTone(  698,   12); wait1Msec( 134);  // Note(F, Duration(16th))
	PlayTone(  622,   12); wait1Msec( 134);  // Note(D#, Duration(16th))
	PlayTone(  698,   12); wait1Msec( 134);  // Note(F, Duration(16th))
	PlayTone(  622,   12); wait1Msec( 134);  // Note(D#, Duration(16th))
	PlayTone(  587,   12); wait1Msec( 134);  // Note(D, Duration(16th))
	PlayTone(  622,   24); wait1Msec( 268);  // Note(D#, Duration(Eighth))
	PlayTone(  587,   12); wait1Msec( 134);  // Note(D, Duration(16th))
	PlayTone(  523,   12); wait1Msec( 134);  // Note(C, Duration(16th))
	PlayTone(  523,   12); wait1Msec( 134);  // Note(C, Duration(16th))
	PlayTone(  523,   12); wait1Msec( 134);  // Note(C, Duration(16th))
	PlayTone(  622,   36); wait1Msec( 402);  // Note(D#, Duration(Eighth .))
	PlayTone(  523,   12); wait1Msec( 134);  // Note(C, Duration(16th))
	PlayTone(  523,   12); wait1Msec( 134);  // Note(C, Duration(16th))
	PlayTone(  523,   12); wait1Msec( 134);  // Note(C, Duration(16th))
	PlayTone(  698,   36); wait1Msec( 402);  // Note(F, Duration(Eighth .))
	PlayTone(  523,   12); wait1Msec( 134);  // Note(C, Duration(16th))
	PlayTone(  523,   12); wait1Msec( 134);  // Note(C, Duration(16th))
	PlayTone(  523,   12); wait1Msec( 134);  // Note(C, Duration(16th))
	PlayTone(  739,   12); wait1Msec( 134);  // Note(F#, Duration(16th))
	PlayTone(  698,   12); wait1Msec( 134);  // Note(F, Duration(16th))
	PlayTone(  622,   12); wait1Msec( 134);  // Note(D#, Duration(16th))
	PlayTone(  698,   12); wait1Msec( 134);  // Note(F, Duration(16th))
	PlayTone(  622,   12); wait1Msec( 134);  // Note(D#, Duration(16th))
	PlayTone(  587,   12); wait1Msec( 134);  // Note(D, Duration(16th))
	PlayTone(  622,   12); wait1Msec( 134);  // Note(D#, Duration(16th))
	PlayTone(  587,   12); wait1Msec( 134);  // Note(D, Duration(16th))
	PlayTone(  523,   12); wait1Msec( 134);  // Note(C, Duration(16th))
	soundPlay = false;
	return;
}

task Zelda1()
{
	//        125 = Tempo
	//          5 = Default octave
	//    Quarter = Default note length
	//        10% = Break between notes
	//
	PlayTone(  932,   43); wait1Msec( 480);  // Note(A#)
	PlayTone(  698,   65); wait1Msec( 720);  // Note(F, Duration(Quarter .))
	PlayTone(  932,   22); wait1Msec( 240);  // Note(A#, Duration(Eighth))
	PlayTone(  932,   11); wait1Msec( 120);  // Note(A#, Duration(16th))
	PlayTone(  784,   11); wait1Msec( 120);  // Note(C6, Duration(16th))
	PlayTone(  880,   11); wait1Msec( 120);  // Note(D6, Duration(16th))
	PlayTone(  933,   11); wait1Msec( 120);  // Note(D#6, Duration(16th))
	PlayTone( 1047,   86); wait1Msec( 960);  // Note(F6, Duration(Half))
	PlayTone(    0,   22); wait1Msec( 240);  // Note(Rest, Duration(Eighth))
	PlayTone( 1047,   22); wait1Msec( 240);  // Note(F6, Duration(Eighth))
	PlayTone( 1047,   16); wait1Msec( 180);  // Note(F6, Duration(16th .))
	PlayTone( 1109,   11); wait1Msec( 120);  // Note(F#6, Duration(16th))
	PlayTone( 1245,   16); wait1Msec( 180);  // Note(G#6, Duration(16th .))
	PlayTone( 1398,  130); wait1Msec(1440);  // Note(A#6, Duration(Half .))
	PlayTone( 1398,   16); wait1Msec( 180);  // Note(A#6, Duration(16th .))
	PlayTone( 1245,   11); wait1Msec( 120);  // Note(G#6, Duration(16th))
	PlayTone( 1109,   16); wait1Msec( 180);  // Note(F#6, Duration(16th .))
	PlayTone( 1245,   32); wait1Msec( 360);  // Note(G#6, Duration(Eighth .))
	PlayTone( 1109,   16); wait1Msec( 180);  // Note(F#6, Duration(16th .))
	PlayTone( 1047,   86); wait1Msec( 960);  // Note(F6, Duration(Half))
	PlayTone( 1047,   43); wait1Msec( 480);  // Note(F6)
	PlayTone(  933,   22); wait1Msec( 240);  // Note(D#6, Duration(Eighth))
	PlayTone(  933,   11); wait1Msec( 120);  // Note(D#6, Duration(16th))
	PlayTone( 1047,   11); wait1Msec( 120);  // Note(F6, Duration(16th))
	PlayTone( 1109,   86); wait1Msec( 960);  // Note(F#6, Duration(Half))
	PlayTone( 1047,   22); wait1Msec( 240);  // Note(F6, Duration(Eighth))
	PlayTone(  933,   22); wait1Msec( 240);  // Note(D#6, Duration(Eighth))
	PlayTone(  831,   22); wait1Msec( 240);  // Note(C#6, Duration(Eighth))
	PlayTone(  831,   11); wait1Msec( 120);  // Note(C#6, Duration(16th))
	PlayTone(  933,   11); wait1Msec( 120);  // Note(D#6, Duration(16th))
	PlayTone( 1047,   86); wait1Msec( 960);  // Note(F6, Duration(Half))
	PlayTone(  933,   22); wait1Msec( 240);  // Note(D#6, Duration(Eighth))
	PlayTone(  831,   22); wait1Msec( 240);  // Note(C#6, Duration(Eighth))
	PlayTone(  784,   22); wait1Msec( 240);  // Note(C6, Duration(Eighth))
	PlayTone(  784,   11); wait1Msec( 120);  // Note(C6, Duration(16th))
	PlayTone(  880,   11); wait1Msec( 120);  // Note(D6, Duration(16th))
	PlayTone(  988,   86); wait1Msec( 960);  // Note(E6, Duration(Half))
	PlayTone( 1175,   43); wait1Msec( 480);  // Note(G6)
	PlayTone( 1047,   22); wait1Msec( 240);  // Note(F6, Duration(Eighth))
	PlayTone(  698,   11); wait1Msec( 120);  // Note(F, Duration(16th))
	PlayTone(  698,   11); wait1Msec( 120);  // Note(F, Duration(16th))
	PlayTone(  698,   22); wait1Msec( 240);  // Note(F, Duration(Eighth))
	PlayTone(  698,   11); wait1Msec( 120);  // Note(F, Duration(16th))
	PlayTone(  698,   11); wait1Msec( 120);  // Note(F, Duration(16th))
	PlayTone(  698,   22); wait1Msec( 240);  // Note(F, Duration(Eighth))
	PlayTone(  698,   11); wait1Msec( 120);  // Note(F, Duration(16th))
	PlayTone(  698,   11); wait1Msec( 120);  // Note(F, Duration(16th))
	PlayTone(  698,   22); wait1Msec( 240);  // Note(F, Duration(Eighth))
	PlayTone(  698,   22); wait1Msec( 240);  // Note(F, Duration(Eighth))
	PlayTone(  932,   43); wait1Msec( 480);  // Note(A#)
	PlayTone(  698,   65); wait1Msec( 720);  // Note(F, Duration(Quarter .))
	PlayTone(  932,   22); wait1Msec( 240);  // Note(A#, Duration(Eighth))
	PlayTone(  932,   11); wait1Msec( 120);  // Note(A#, Duration(16th))
	PlayTone(  784,   11); wait1Msec( 120);  // Note(C6, Duration(16th))
	PlayTone(  880,   11); wait1Msec( 120);  // Note(D6, Duration(16th))
	PlayTone(  933,   11); wait1Msec( 120);  // Note(D#6, Duration(16th))
	PlayTone( 1047,   86); wait1Msec( 960);  // Note(F6, Duration(Half))
	PlayTone(    0,   22); wait1Msec( 240);  // Note(Rest, Duration(Eighth))
	PlayTone( 1047,   22); wait1Msec( 240);  // Note(F6, Duration(Eighth))
	PlayTone( 1047,   16); wait1Msec( 180);  // Note(F6, Duration(16th .))
	PlayTone( 1109,   11); wait1Msec( 120);  // Note(F#6, Duration(16th))
	PlayTone( 1245,   16); wait1Msec( 180);  // Note(G#6, Duration(16th .))
	PlayTone( 1398,  130); wait1Msec(1440);  // Note(A#6, Duration(Half .))
	PlayTone( 1108,   43); wait1Msec( 480);  // Note(C#7)
	PlayTone( 1046,   43); wait1Msec( 480);  // Note(C7)
	PlayTone( 1320,   86); wait1Msec( 960);  // Note(A6, Duration(Half))
	PlayTone( 1047,   43); wait1Msec( 480);  // Note(F6)
	PlayTone( 1109,  130); wait1Msec(1440);  // Note(F#6, Duration(Half .))
	PlayTone( 1398,   43); wait1Msec( 480);  // Note(A#6)
	PlayTone( 1320,   43); wait1Msec( 480);  // Note(A6)
	PlayTone( 1047,   86); wait1Msec( 960);  // Note(F6, Duration(Half))
	PlayTone( 1047,   43); wait1Msec( 480);  // Note(F6)
	PlayTone( 1109,  130); wait1Msec(1440);  // Note(F#6, Duration(Half .))
	PlayTone( 1398,   43); wait1Msec( 480);  // Note(A#6)
	PlayTone( 1320,   43); wait1Msec( 480);  // Note(A6)
	PlayTone( 1047,   86); wait1Msec( 960);  // Note(F6, Duration(Half))
	PlayTone(  880,   43); wait1Msec( 480);  // Note(D6)
	PlayTone(  933,  130); wait1Msec(1440);  // Note(D#6, Duration(Half .))
	PlayTone( 1109,   43); wait1Msec( 480);  // Note(F#6)
	PlayTone( 1047,   43); wait1Msec( 480);  // Note(F6)
	PlayTone(  831,   86); wait1Msec( 960);  // Note(C#6, Duration(Half))
	PlayTone(  932,   43); wait1Msec( 480);  // Note(A#)
	PlayTone(  784,   43); wait1Msec( 480);  // Note(C6)
	PlayTone(  880,   11); wait1Msec( 120);  // Note(D6, Duration(16th))
	PlayTone(  988,   86); wait1Msec( 960);  // Note(E6, Duration(Half))
	PlayTone( 1175,   43); wait1Msec( 480);  // Note(G6)
	PlayTone( 1047,   22); wait1Msec( 240);  // Note(F6, Duration(Eighth))
	PlayTone(  698,   11); wait1Msec( 120);  // Note(F, Duration(16th))
	PlayTone(  698,   11); wait1Msec( 120);  // Note(F, Duration(16th))
	PlayTone(  698,   22); wait1Msec( 240);  // Note(F, Duration(Eighth))
	PlayTone(  698,   11); wait1Msec( 120);  // Note(F, Duration(16th))
	PlayTone(  698,   11); wait1Msec( 120);  // Note(F, Duration(16th))
	PlayTone(  698,   22); wait1Msec( 240);  // Note(F, Duration(Eighth))
	PlayTone(  698,   11); wait1Msec( 120);  // Note(F, Duration(16th))
	PlayTone(  698,   11); wait1Msec( 120);  // Note(F, Duration(16th))
	PlayTone(  698,   22); wait1Msec( 240);  // Note(F, Duration(Eighth))
	PlayTone(  698,   22); wait1Msec( 240);  // Note(F, Duration(Eighth))
	soundPlay = false;
	return;
}

//Check if speed locking is enabled
void setLock () {
	if (vexRT[Btn7LXmtr2] == 1) {
		LOCK = true;
		} else if (vexRT[Btn7UXmtr2] == 1) {
		LOCK = false;
	}
}

//Shoot function shoots balls at a specified rate in autonomous
void ushoot (int speed, int time) {
	wait1Msec(DELAY_TIME);
	motor[shooter1] = speed;
	motor[shooter3] = speed;
	wait1Msec(time);
	motor[shooter1] = 0;
	motor[shooter3] = 0;
}

//shoot function assigns launcher speed to 127
void shoot() {
	if (SensorValue[skills] == 0) {
		if (SensorValue[detector] == 1) {
			motor[shooter1] = NETSPEED;
			motor[shooter3] = NETSPEED;
			}	else {
			if (motor[shooter1] > (COOLSPEED)) {
				for (int i = motor[shooter1]; i >= (COOLSPEED); i--) {
					motor[shooter1] = i;
					motor[shooter3] = i;
				}
				}	else {
				motor[shooter1] = COOLSPEED;
				motor[shooter3] = COOLSPEED;
			}
		}
  } else {
		if (SensorValue[detector] == 1) {
			motor[shooter1] = SHOOTSPEED;
			motor[shooter3] = SHOOTSPEED;
			}	else {
			if (motor[shooter1] > (SHOOTSPEED - 10)) {
				for (int i = motor[shooter1]; i >= (SHOOTSPEED - 10); i--) {
					motor[shooter1] = i;
					motor[shooter3] = i;
				}
				}	else {
				motor[shooter1] = SHOOTSPEED - 10;
				motor[shooter3] = SHOOTSPEED - 10;
			}
		}
	}
}

void shoot2()
{
	motor[shooter1] = SHOOTSPEED;
	motor[shooter3] = SHOOTSPEED;
}

//Does this need a break function?
void autoturnAngle(float turn) {
turning:
	while (SensorValue[gyro] > (11 + turn) || SensorValue[gyro] < (-11 + turn)) {
		if ((SensorValue[gyro] > (11 + turn) && SensorValue[gyro] <= (1800 + turn)) || (SensorValue[gyro] < (-1800 + turn))) {
			if (abs(SensorValue[gyro]) > 1800) {
				motor[FR] = 30 + floor((3600-abs((SensorValue[gyro]-turn))*127)/450);
				motor[BR] = 30 + floor((3600-abs((SensorValue[gyro]-turn))*127)/450);
				motor[FL] = -30 - floor((3600-abs((SensorValue[gyro]-turn))*127)/450);
				motor[BL] = -30 - floor((3600-abs((SensorValue[gyro]-turn))*127)/450);
				} else {
				motor[FR] = 30 + floor((abs((SensorValue[gyro]-turn))*127)/450);
				motor[BR] = 30 + floor((abs((SensorValue[gyro]-turn))*127)/450);
				motor[FL] = -30 - floor((abs((SensorValue[gyro]-turn))*127)/450);
				motor[BL] = -30 - floor((abs((SensorValue[gyro]-turn))*127)/450);
			}
			}	else if ((SensorValue[gyro] < (-11 + turn) && SensorValue[gyro] >= (-1800 + turn)) || (SensorValue[gyro] > (1800 + turn))) {
			if (abs(SensorValue[gyro]) > 1800) {
				motor[FR] = -30 - floor((3600-abs((SensorValue[gyro]-turn))*127)/450);
				motor[BR] = -30 - floor((3600-abs((SensorValue[gyro]-turn))*127)/450);
				motor[FL] = 30 + floor((3600-abs((SensorValue[gyro]-turn))*127)/450);
				motor[BL] = 30 + floor((3600-abs((SensorValue[gyro]-turn))*127)/450);
				} else {
				motor[FR] = -30 - floor((abs((SensorValue[gyro]-turn))*127)/450);
				motor[BR] = -30 - floor((abs((SensorValue[gyro]-turn))*127)/450);
				motor[FL] = 30 + floor((abs((SensorValue[gyro]-turn))*127)/450);
				motor[BL] = 30 + floor((abs((SensorValue[gyro]-turn))*127)/450);
			}
		}
	}
	motor[FR] = 0;
	motor[BR] = 0;
	motor[FL] = 0;
	motor[BL] = 0;
	//wait1Msec(300);
	//if (SensorValue[gyro] > (51 + turn) || SensorValue[gyro] < (-51 + turn)) {
	//goto turning;
	//}
}

int coordX;
int coordY;
int goalX;
int goalY;
float DISTANCE;
float TURNANGLE;
float UNMODIFIEDSPEED;
//127 = 120 RPM
//fix factor
void autoturnToGoal() {
	if (COLOR == 0) { //blue
		goalX = DIMENSION;
		goalY = DIMENSION;
		coordX = DIMENSION - SensorValue[sonarX];
		coordY = SensorValue[sonarY];
		DISTANCE = sqrt(pow((goalX - coordX),2)+pow((goalY - coordY),2));
		TURNANGLE = -(asin((goalX - coordX)/DISTANCE)*(3600/(2*PI))); //negative?
		autoturnAngle(TURNANGLE);
		UNMODIFIEDSPEED = sqrt((DISTANCE*981)/sinDegrees(2*ANGLE));
		//SHOOTSPEED = floor((UNMODIFIEDSPEED * 60 * 127)/(120*(2*PI*RADIUS)));
		//Code to convert to SHOOTSPEED goes here
		} else { //red
		goalX = 0;
		goalY = DIMENSION;
		coordX = DIMENSION - SensorValue[sonarX];
		coordY = SensorValue[sonarY];
		DISTANCE = sqrt(pow((coordX - goalX),2)+pow((coordY - goalY),2));
		TURNANGLE = -(asin((coordX-goalX)/DISTANCE)*(3600/(2*PI))); //positive?
		autoturnAngle(TURNANGLE);
		UNMODIFIEDSPEED = sqrt((DISTANCE*981)/sinDegrees(2*ANGLE));
		//SHOOTSPEED = floor((UNMODIFIEDSPEED * 60 * 127)/(120*(2*PI*RADIUS)));
		//Code to convert to SHOOTSPEED goes here
	}
}

void tank() {
	motor[FL] = vexRT[Ch2];
	motor[BL] = vexRT[Ch2];
	motor[FR] = vexRT[Ch3];
	motor[BR] = vexRT[Ch3];
}

int X2 = 0, Y1 = 0, X1 = 0, threshold = 15;
void tankMecanum() {
	//Create "deadzone" for Y1/Ch3
	if (abs(vexRT[Ch3]) > threshold) {
		Y1 = vexRT[Ch3];
		} else {
		Y1 = 0;
	}
	//Create "deadzone" for X1/Ch4
	if (abs(vexRT[Ch4]) > threshold) {
		X1 = -vexRT[Ch4];
		} else {
		X1 = 0;
	}
	//Create "deadzone" for X2/Ch1
	if (abs(vexRT[Ch1]) > threshold) {
		X2 = -vexRT[Ch1];
		} else {
		X2 = 0;
	}
	//Remote Control Commands
	motor[FR] = Y1 - X2 - X1;
	motor[BR] =  Y1 - X2 + X1;
	motor[FL] = Y1 + X2 + X1;
	motor[BL] =  Y1 + X2 - X1;
}

void tankMotion() {
	if (abs(vexRT[AccelX]) > abs(vexRT[AccelY])) {
		motor[BR] = (-(vexRT[AccelX])) / 2;
		motor[FR] = (-(vexRT[AccelX])) / 2;
		motor[BL] = (vexRT[AccelX]) / 2;
		motor[FL] = (vexRT[AccelX]) / 2;
		} else if (abs(vexRT[AccelY]) >= abs(vexRT[AccelX])) {
		motor[BR] = (-(vexRT[AccelY]));
		motor[FR] = (-(vexRT[AccelY]));
		motor[BL] = (-(vexRT[AccelY]));
		motor[FL] = (-(vexRT[AccelY]));
	}
}

void tankMotionMecanum() {
	if (abs(vexRT[AccelY]) > threshold) {
		Y1 = -(vexRT[AccelY]);
		} else {
		Y1 = 0;
	}
	//Create "deadzone" for X1/Ch4
	if ((abs(vexRT[AccelX]) > threshold) && (vexRT[Btn5DXmtr2] == 0)) {
		X1 = (vexRT[AccelX]);
		} else {
		X1 = 0;
	}
	//Create "deadzone" for X2/Ch1
	if ((abs(vexRT[AccelX]) > threshold) && (vexRT[Btn5DXmtr2] == 1)) {
		X2 = (vexRT[AccelX])/2;
		} else {
		X2 = 0;
	}
	//Remote Control Commands
	motor[FR] = Y1 - X2 - X1;
	motor[BR] =  Y1 - X2 + X1;
	motor[FL] = Y1 + X2 + X1;
	motor[BL] =  Y1 + X2 - X1;
}

task slowdown() {
	for (int i = motor[shooter1]; i >= 0; i--) {
		motor[shooter1] = i;
		motor[shooter3] = i;
	}
}

////uTurn function assigns turntable speed and direction to joystick X direction
//void uTurn() {
//	motor[turntable] = vexRT[Ch4];
//}

//uShootMotion function assigns launcher speed to Y direction accelerometer
//void uShootMotion() {
//	if (vexRT[AccelY] < 0) {
//		motor[shooter1] = ((-vexRT[AccelY] * 127)/90);
//		motor[shooter2] = ((-vexRT[AccelY] * 127)/90);
//		} else {
//		motor[shooter1] = 0;
//		motor[shooter2] = 0;
//	}
//}

//int flashValue = 0;

//task flashlightCtrl () { //Control flashlight
//	while (true) {
//		if (vexRT[Ch2] > 10 && flashValue < 127) {
//			flashValue = flashValue + 1;
//			motor[flashlight] = flashValue;
//			}	else if (vexRT[Ch2] < -10 && flashValue > -1) {
//			flashValue = flashValue - 1;
//			motor[flashlight] = flashValue;
//		}
//		wait1Msec(50);
//	}
//}

//int pos = 0;
//int num = 32;
//task typer () { //A button test
//	pos = 0;
//	clearLCDLine(0);
//	clearLCDLine(1);
//	while (true) {
//		bLCDBacklight = true;
//		num = 32;
//		if (pos < 16) {
//			displayLCDPos(0,pos);
//			while (SensorValue[lever] == 0) {
//				displayNextLCDChar(num);
//				displayLCDPos(0,pos);
//				wait1Msec(50);
//				if (SensorValue[button] == 1 && (num < 90 && num >= 65)) {
//					num = num + 1;
//					while (SensorValue[button] == 1) {
//					}
//					}	else if (SensorValue[button] == 1 && (num >= 90 || num < 65)) {
//					num = 65;
//					while (SensorValue[button] == 1) {
//					}
//				}
//			}
//			pos = pos + 1;
//			while (SensorValue[lever] == 1) {
//			}
//			} else if (pos < 32) {
//			displayLCDPos(1,pos - 16);
//			while (SensorValue[lever] == 0) {
//				displayNextLCDChar(num);
//				displayLCDPos(1,pos - 16);
//				wait1Msec(50);
//				if (SensorValue[button] == 1 && (num < 90 && num >= 65)) {
//					num = num + 1;
//					while (SensorValue[button] == 1) {
//					}
//					}	else if (SensorValue[button] == 1 && (num >= 90 || num < 65)) {
//					num = 65;
//					while (SensorValue[button] == 1) {
//					}
//				}
//			}
//			pos = pos + 1;
//			while (SensorValue[lever] == 1) {
//			}
//			} else {
//			pos = 0;
//			clearLCDLine(0);
//			clearLCDLine(1);
//		}
//	}
//}

//task music () {
//	while (true) {
//		if(bSoundQueueAvailable)  // if there is still space in the Sound Queue:
//		{
//			playImmediateTone(abs(SensorValue[sonar])/4, 50);  // play tone according to sensor readings
//			wait1Msec(500);
//		}
//	}
//}

//Debug task alerts user of robot shooters active
task debug () {
	clearLCDLine(0);
	clearLCDLine(1);
	while (true) {
		bLCDBacklight = true;									// Turn on LCD Backlight
		displayLCDPos(0,0);
		string display1;
		sprintf(display1, "FIRING!!! %3d", TIMER);
		displayNextLCDString(display1);
		displayLCDPos(1,0);
		string display2;
		sprintf(display2, "C3:%4d  C2:%4d", vexRT[Ch3], vexRT[Ch2]);
		displayNextLCDString(display2);
	}
}

task autoSkills () {
	clearLCDLine(0);
	clearLCDLine(1);
	while (true) {
		bLCDBacklight = true;									// Turn on LCD Backlight
		displayLCDPos(0,0);
		string display1;
		sprintf(display1, "Balls: %2d", fired);
		displayNextLCDString(display1);
		displayLCDPos(1,0);
		string display2;
		sprintf(display2, "Auto Skills");
		displayNextLCDString(display2);
	}
}

////debugMotion task alerts user of robot shooters active with accelerometer
//task debugMotion () {
//	clearLCDLine(0);
//	clearLCDLine(1);
//	while (true) {
//		bLCDBacklight = true;									// Turn on LCD Backlight
//		displayLCDPos(0,0);
//		string display1;
//		sprintf(display1, "FIRING!!! %3d", TIMER);
//		displayNextLCDString(display1);
//		displayLCDPos(1,0);
//		string display2;
//		sprintf(display2, "CtrlAcc:%4d", vexRT[AccelY]);
//		displayNextLCDString(display2);
//	}
//}

//Debug2 task alerts user of lift mechanism activating
task debug2 () {
	clearLCDLine(0);
	clearLCDLine(1);
	while (true) {
		bLCDBacklight = true;									// Turn on LCD Backlight
		displayLCDPos(0,0);
		string display1;
		sprintf(display1, "LIFTING!!! %3d", TIMER);
		displayNextLCDString(display1);
		displayLCDPos(1,0);
		string display2;
		sprintf(display2, "C3:%4d  C2:%4d", vexRT[Ch3], vexRT[Ch2]);
		displayNextLCDString(display2);
	}
}

//NoDebug task alerts user of game time and battery level
task nodebug () {
	clearLCDLine(0);
	clearLCDLine(1);
	while (true) {
		bLCDBacklight = true;									// Turn on LCD Backlight
		string mainBattery;
		displayLCDPos(0,0);
		string display1;
		sprintf(display1, "TIMER: %3d", TIMER);
		displayNextLCDString(display1);
		displayLCDPos(1,0);
		displayNextLCDString("Battery : ");
		sprintf(mainBattery, "%1.2f%c", nImmediateBatteryLevel/1000.0,'V'); //Build the value to be displayed
		displayNextLCDString(mainBattery);
	}
}

//ButtonDebug task alerts user of joystick values
task buttonDebug() {
	clearLCDLine(0);
	clearLCDLine(1);
	while (true) {
		bLCDBacklight = true;
		displayLCDPos(0,0);
		string display1;
		sprintf(display1, "C4:%4d  C1:%4d", vexRT[Ch4], vexRT[Ch1]);
		displayNextLCDString(display1);
		displayLCDPos(1,0);
		string display2;
		sprintf(display2, "C3:%4d  C2:%4d", vexRT[Ch3], vexRT[Ch2]);
		displayNextLCDString(display2);
	}
}

//SensorDebug task alerts user of gyro/accelerometer values
task sensorDebug() {
	clearLCDLine(0);
	clearLCDLine(1);
	while (true) {
		bLCDBacklight = true;
		displayLCDPos(0,0);
		string display1;
		sprintf(display1, "G: %4d  X: %4d", (SensorValue[gyro]/10), SensorValue[Xaccel]);
		displayNextLCDString(display1);
		displayLCDPos(1,0);
		string display2;
		sprintf(display2, "Y: %4d  Z: %4d", SensorValue[Yaccel], SensorValue[Zaccel]);
		displayNextLCDString(display2);
	}
}

//OtherDebug task alerts user of line sensor and motor values
task otherDebug() {
	clearLCDLine(0);
	clearLCDLine(1);
	while (true) {
		bLCDBacklight = true;
		displayLCDPos(0,0);
		string display1;
		sprintf(display1, "Line : %9d", SensorValue[detector]);
		displayNextLCDString(display1);
		displayLCDPos(1,0);
		string display2;
		sprintf(display2, "S1:%4d  S2:%4d", motor[shooter1], motor[shooter2]);
		displayNextLCDString(display2);
	}
}


/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

//Pre_auton is used to reset sensor values for accuracy
void pre_auton()
{
	nVolume = 10000;
	if (SensorValue[colorChoice] == 0) {
		COLOR = 0; //BLUE
		} else {
		COLOR = 1; //RED
	}
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
	// Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;
	//Completely clear out any previous sensor readings by setting the port to "sensorNone"
	SensorType[gyro] = sensorNone;
	SensorType[detector] = sensorNone;
	SensorType[Xaccel] = sensorNone;
	SensorType[Yaccel] = sensorNone;
	SensorType[Zaccel] = sensorNone;
	wait1Msec(1000);
	//Reconfigure sensors and allow time for ROBOTC to calibrate it
	SensorType[gyro] = sensorGyro;
	SensorType[detector] = sensorTouch;
	SensorType[Xaccel] = sensorAccelerometer;
	SensorType[Yaccel] = sensorAccelerometer;
	SensorType[Zaccel] = sensorAccelerometer;
	//wait1Msec(2000);
	displayLCDPos(0,0);
	displayNextLCDString("CALIBRATED");
	playSound(soundLowBuzz);
	//wait1Msec(1000);
	startTask(sensorDebug);
	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

//Autonomous tracks line sensor to know when it has a ball, then fires it
task autonomous() {
	slaveMotor(shooter2, shooter1);
	slaveMotor(shooter4, shooter3);

	stopTask(sensorDebug);
	nVolume = 100;
	if (SensorValue[skills] == 0) {
	  startTask(autoSkills);
		motor[shooter1] = COOLSPEED;
		motor[shooter3] = COOLSPEED;
		SHOOTSPEED = COOLSPEED;
		wait1Msec(500);
		while (true) {
			if (SensorValue[detector] == 1) {
				motor[shooter1] = NETSPEED;
				motor[shooter3] = NETSPEED;
				motor[intake] = 127;
				motor[startIntake] = 127;
				SHOOTSPEED = NETSPEED;
			}	else {
				if (SHOOTSPEED > COOLSPEED) {
					for (int i = SHOOTSPEED; i >= COOLSPEED; i--) {
						motor[shooter1] = i;
						motor[shooter3] = i;
						motor[intake] = 127;
						motor[startIntake] = 127;
					}
					SHOOTSPEED = COOLSPEED;
					}	else {
					motor[shooter1] = COOLSPEED;
					motor[shooter3] = COOLSPEED;
					motor[intake] = 127;
					motor[startIntake] = 127;
					SHOOTSPEED = COOLSPEED;
				}
			}
			motor[intake] = 127;
			motor[startIntake] = 127;
			//if (SensorValue[detector] == 1 && sensed == false) {
			//	fired = fired + 1;
			//	sensed = true;
			//	}	else if (SensorValue[detector] == 0 && sensed == true) {
			//	sensed = false;
			//}
		}
		wait1Msec(500);
		stopTask(autoSkills);
		motor[intake] = 0;
		motor[startIntake] = 0;
		for (int i = SHOOTSPEED; i >= 0; i--) {
			motor[shooter1] = i;
			motor[shooter3] = i;
		}
		autoturnAngle(-900); //-900
		motor[FR] = 127;
		motor[FL] = 127;
		motor[BR] = 127;
		motor[BL] = 127;
		wait1Msec(6000);
		motor[FR] = 0;
		motor[FL] = 0;
		motor[BR] = 0;
		motor[BL] = 0;
		autoturnAngle(0); //0
		motor[shooter1] = COOLSPEED;
		motor[shooter3] = COOLSPEED;
		SHOOTSPEED = COOLSPEED;
		wait1Msec(500);
		while (true) {
			if (SensorValue[detector] == 1) {
				motor[shooter1] = NETSPEED;
				motor[shooter3] = NETSPEED;
				SHOOTSPEED = NETSPEED;
				}	else {
				if (SHOOTSPEED > COOLSPEED) {
					for (int i = SHOOTSPEED; i >= COOLSPEED; i--) {
						motor[shooter1] = i;
						motor[shooter3] = i;
					}
					SHOOTSPEED = COOLSPEED;
					}	else {
					motor[shooter1] = COOLSPEED;
					motor[shooter3] = COOLSPEED;
					SHOOTSPEED = COOLSPEED;
				}
			}
			motor[intake] = 127;
			motor[startIntake] = 127;
		}
		} else {
		//startTask(ffvii_boss);
		//motor[FR] = 127;
		//motor[FL] = 127;
		//motor[BR] = 127;
		//motor[BL] = 127;
		//wait1Msec(2000);
		//motor[FR] = 0;
		//motor[FL] = 0;
		//motor[BR] = 0;
		//motor[BL] = 0;
		//if (COLOR == 0) {
		//	autoturnAngle(-900);
		//	} else {
		//	autoturnAngle(900);
		//}
		startTask(Zelda1);
		//REMOVE THIS BLOCK IF NO FORWARD MOVEMENT IS NEEDED
		motor[FR] = 127;
		motor[FL] = 127;
		motor[BR] = 127;
		motor[BL] = 127;
		wait1Msec(1000); //CHANGE THIS NUMBER IF ROBOT NEEDS MORE/LESS MOVEMENT
		motor[FR] = 0;
		motor[FL] = 0;
		motor[BR] = 0;
		motor[BL] = 0;
		//END OF BLOCK
		//autoturnAngle(0);
		//autoturnToGoal();
		motor[shooter1] = 100;
		motor[shooter3] = 100;
		wait1Msec(3000);
		motor[shooter1] = 100;
		motor[shooter3] = 100;
		motor[intake] = 127;
		motor[startIntake] = 127;
		wait1Msec(5000);
		for (int i = 100; i >= 0; i--) {
			motor[shooter1] = i;
			motor[shooter3] = i;
		}
		motor[intake] = 0;
		motor[startIntake] = 0;
		stopTask(Zelda1);
		//while (true) {
		//	if (SensorValue[line] <= LIGHT_VALUE) { //Check if it has a ball
		//		stopTask(nodebug);
		//		startTask(debug); // Alert user of firing
		//		ushoot(127,4000); //Fire ball
		//		//stopTask(debug);
		//	}
		//	else {
		//		stopTask(debug); //Alert user of not firing
		//		startTask(nodebug);
		//	}
		//}
	}
	SHOOTSPEED = 100;
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

//User control handles main movement and debugging
task usercontrol() {
	slaveMotor(shooter2, shooter1);
	slaveMotor(shooter4, shooter3);
	//startTask(music); //Sound fun
	startTask(update); //Begin clock
	//startTask(flashlightCtrl); //Begin flashlight control
	nVolume = 100;
	while (true) {
		setLock(); //Check to see if speed lock enabled
		if ((vexRT[Btn8D] == 1) && soundPlay == false) {
			soundPlay = true;
			startTask(ffvii_boss);
		}
		//if (vexRT[Btn8D] == 1) {
		//	autoturnAngle(0);
		//	autoturnToGoal();
		//}
		if (LOCK == true) {
			if (vexRT[Btn7RXmtr2] == 1) {
				if (SensorValue[motion] == 0) {
					tankMotion();
					} else {
					tank();
				}
			}
			}	else {
			if (SensorValue[motion] == 0) {
				tankMotion();
				} else {
				tank();
			}
		}
		//uTurn(); //Check to see if it should turn
		if (vexRT[Btn5UXmtr2] == 1) { //Button needed to confirm
			stopTask(nodebug);
			stopTask(buttonDebug);
			stopTask(sensorDebug);
			stopTask(otherDebug);
			stopTask(debug2);
			//stopTask(typer);
			startTask(debug);
			shoot();
			pressed = true;
		}
		if (vexRT[Btn5U] == 1) {
			motor[intake] = 127;
			motor[startIntake] = 127;
		}
		else if (vexRT[Btn5D] == 1) {
			motor[intake] = -127;
			motor[startIntake] = -127;
		}
		else if (vexRT[Btn5U] == 0) {
			motor[intake] = 0;
			motor[startIntake] = 0;
		}
		if (vexRT[Btn7U] == 1) {
			SHOOTSPEED = 100;
		}
		if (vexRT[Btn7L] == 1) {
			SHOOTSPEED = 75;
		}
		if (vexRT[Btn7R] == 1) {
			SHOOTSPEED = 50;
		}
		if (vexRT[Btn7D] == 1) {
			SHOOTSPEED = 25;
		}
		if (vexRT[Btn8L] == 1) {
			autoturnAngle(0);
		}
		if (vexRT[Btn6U] == 1) { //Failsafe if sensor breaks
			stopTask(nodebug);
			stopTask(buttonDebug);
			stopTask(sensorDebug);
			stopTask(otherDebug);
			stopTask(debug2);
			//stopTask(typer);
			startTask(debug);
			shoot2();
			pressed = true;
		}
		else if (vexRT[Btn6U] == 0 && motor[shooter1] > 0 && pressed == true) {
			pressed = false;
			startTask(slowdown);
		}
		else if (vexRT[Btn7DXmtr2] == 1 && TIMER >= 100) { //Activate lift only at end
			stopTask(nodebug);
			stopTask(buttonDebug);
			stopTask(sensorDebug);
			stopTask(otherDebug);
			stopTask(debug);
			//stopTask(typer);
			startTask(debug2);
		}
		else if (vexRT[Btn8UXmtr2] == 1 || nLCDButtons == 1){ //Begin NoDebug task
			stopTask(debug);
			stopTask(buttonDebug);
			stopTask(sensorDebug);
			stopTask(otherDebug);
			stopTask(debug2);
			//stopTask(typer);
			startTask(nodebug);
		}

		else if (vexRT[Btn8RXmtr2] == 1 || nLCDButtons == 2) { //Begin ButtonDebug task
			stopTask(debug);
			stopTask(nodebug);
			stopTask(sensorDebug);
			stopTask(otherDebug);
			stopTask(debug2);
			//stopTask(typer);
			startTask(buttonDebug);
		}
		else if (vexRT[Btn8DXmtr2] == 1 || nLCDButtons == 4) { //Begin SensorDebug task
			stopTask(debug);
			stopTask(nodebug);
			stopTask(otherDebug);
			stopTask(buttonDebug);
			stopTask(debug2);
			//stopTask(typer);
			startTask(sensorDebug);
		}
		else if (vexRT[Btn8LXmtr2] == 1 || nLCDButtons == 3) { //Begin OtherDebug task
			stopTask(debug);
			stopTask(nodebug);
			stopTask(buttonDebug);
			stopTask(sensorDebug);
			stopTask(debug2);
			//stopTask(typer);
			startTask(otherDebug);
		}
		else if (nLCDButtons == 7) {
			stopTask(debug);
			stopTask(nodebug);
			stopTask(buttonDebug);
			stopTask(sensorDebug);
			stopTask(debug2);
			stopTask(otherDebug);
			//startTask(typer);
		}
	}
}
