#pragma config(Sensor, in1,    light,          sensorReflection)
#pragma config(Sensor, in2,    gyro,           sensorGyro)
#pragma config(Sensor, in3,    line,           sensorLineFollower)
#pragma config(Sensor, in4,    Xaccel,         sensorAccelerometer)
#pragma config(Sensor, in5,    Yaccel,         sensorAccelerometer)
#pragma config(Sensor, in6,    Zaccel,         sensorAccelerometer)
#pragma config(Sensor, in8,    motion,         sensorAnalog)
#pragma config(Motor,  port1,           turntable,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           shooter1,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           lift1,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           lift2,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           lift3,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           lift4,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           lift5,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           lift6,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           shooter2,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          flashlight,    tmotorVexFlashlight, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

int LIGHT_VALUE = 2500; //The value of light the robot needs or less to shoot
int DELAY_TIME = 100; //Time between detection of ball and shoot
int TIMER = 0;

task update () {
	while (true) {
		wait1Msec(1000);
		TIMER = TIMER + 1;
	}
}

void shoot (int speed, int time) { //Function to shoot spheres from launcher
	wait1Msec(DELAY_TIME);
	motor[shooter1] = speed;
	motor[shooter2] = speed;
	wait1Msec(time);
	motor[shooter1] = 0;
	motor[shooter2] = 0;
}

void uShoot() {
	motor[shooter1] = vexRT[Ch2];
	motor[shooter2] = vexRT[Ch2];
}

void uTurn() {
	motor[turntable] = vexRT[Ch4];
}

void uShootMotion() {
	if (vexRT[AccelY] < 0) {
		motor[shooter1] = ((-vexRT[AccelY] * 127)/90);
		motor[shooter2] = ((-vexRT[AccelY] * 127)/90);
	} else {
		motor[shooter1] = 0;
		motor[shooter2] = 0;
	}
}

task debug () {
	playSound(soundBeepBeep);
	clearLCDLine(0);
	clearLCDLine(1);
	while (true) {
		bLCDBacklight = true;									// Turn on LCD Backlight
		displayLCDPos(0,0);
		string display1;
		sprintf(display1, "FIRING!!! %3d", TIMER);
		displayNextLCDString(display1);
		displayLCDPos(1,0);
		string display2;
		sprintf(display2, "C3:%4d  C2:%4d", vexRT[Ch3], vexRT[Ch2]);
		displayNextLCDString(display2);
	}
}

task debugMotion () {
	playSound(soundBeepBeep);
	clearLCDLine(0);
	clearLCDLine(1);
	while (true) {
		bLCDBacklight = true;									// Turn on LCD Backlight
		displayLCDPos(0,0);
		string display1;
		sprintf(display1, "FIRING!!! %3d", TIMER);
		displayNextLCDString(display1);
		displayLCDPos(1,0);
		string display2;
		sprintf(display2, "CtrlAcc:%4d", vexRT[AccelY]);
		displayNextLCDString(display2);
	}
}

task debug2 () {
	playSound(soundBlip);
	clearLCDLine(0);
	clearLCDLine(1);
	while (true) {
		bLCDBacklight = true;									// Turn on LCD Backlight
		displayLCDPos(0,0);
		string display1;
		sprintf(display1, "LIFTING!!! %3d", TIMER);
		displayNextLCDString(display1);
		displayLCDPos(1,0);
		string display2;
		sprintf(display2, "C3:%4d  C2:%4d", vexRT[Ch3], vexRT[Ch2]);
		displayNextLCDString(display2);
	}
}

task nodebug () {
	clearLCDLine(0);
	clearLCDLine(1);
	while (true) {
		bLCDBacklight = true;									// Turn on LCD Backlight
		string mainBattery;
		displayLCDPos(0,0);
		string display1;
		sprintf(display1, "TIMER: %3d", TIMER);
		displayNextLCDString(display1);
		displayLCDPos(1,0);
		displayNextLCDString("Battery : ");
		sprintf(mainBattery, "%1.2f%c", nImmediateBatteryLevel/1000.0,'V'); //Build the value to be displayed
		displayNextLCDString(mainBattery);
	}
}

task buttonDebug() {
	clearLCDLine(0);
	clearLCDLine(1);
	while (true) {
		bLCDBacklight = true;
		displayLCDPos(0,0);
		string display1;
		sprintf(display1, "C4:%4d  C1:%4d", vexRT[Ch4], vexRT[Ch1]);
		displayNextLCDString(display1);
		displayLCDPos(1,0);
		string display2;
		sprintf(display2, "C3:%4d  C2:%4d", vexRT[Ch3], vexRT[Ch2]);
		displayNextLCDString(display2);
	}
}

task sensorDebug() {
	clearLCDLine(0);
	clearLCDLine(1);
	while (true) {
		bLCDBacklight = true;
		displayLCDPos(0,0);
		string display1;
		sprintf(display1, "G: %4d  X: %4d", (SensorValue[gyro]/10), SensorValue[Xaccel]);
		displayNextLCDString(display1);
		displayLCDPos(1,0);
		string display2;
		sprintf(display2, "Y: %4d  Z: %4d", SensorValue[Yaccel], SensorValue[Zaccel]);
		displayNextLCDString(display2);
	}
}

task otherDebug() {
	clearLCDLine(0);
	clearLCDLine(1);
	while (true) {
		bLCDBacklight = true;
		displayLCDPos(0,0);
		string display1;
		sprintf(display1, "Line : %9d", SensorValue[line]);
		displayNextLCDString(display1);
		displayLCDPos(1,0);
		string display2;
		sprintf(display2, "P2:%4d  P9:%4d", motor[shooter1], motor[shooter2]);
		displayNextLCDString(display2);
	}
}


/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
  // Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;
	//Completely clear out any previous sensor readings by setting the port to "sensorNone"
 	SensorType[gyro] = sensorNone;
 	SensorType[line] = sensorNone;
 	SensorType[Xaccel] = sensorNone;
 	SensorType[Yaccel] = sensorNone;
 	SensorType[Zaccel] = sensorNone;
 	wait1Msec(1000);
 	//Reconfigure sensors and allow time for ROBOTC to calibrate it
 	SensorType[gyro] = sensorGyro;
 	SensorType[line] = sensorLineFollower;
 	SensorType[Xaccel] = sensorAccelerometer;
 	SensorType[Yaccel] = sensorAccelerometer;
 	SensorType[Zaccel] = sensorAccelerometer;
 	wait1Msec(2000);
 	displayLCDPos(0,0);
 	displayNextLCDString("CALIBRATED");
 	wait1Msec(1000);
 	startTask(sensorDebug);
	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous() {
	stopTask(sensorDebug);
  while (true) {
  	if (SensorValue[line] <= LIGHT_VALUE) {
  		stopTask(nodebug);
  		startTask(debug);
  		shoot(127,4000);
  		stopTask(debug);
  	}
  	else {
  		stopTask(debug);
  		startTask(nodebug);
  	}
  }
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol() {
	startTask(update);
	while (true) {
		uTurn();
		if (SensorValue[line] <= LIGHT_VALUE) {
  		if (vexRT[Btn5D] == 1 || vexRT[Btn5U] == 1) {
  			stopTask(nodebug);
  			stopTask(buttonDebug);
  			stopTask(sensorDebug);
  			stopTask(otherDebug);
  			stopTask(debug2);
  			if (SensorValue[motion] > 1) {
  				startTask(debug);
  				uShoot();
  			}
  			else if (SensorValue[motion] == 0) {
  				startTask(debugMotion);
  				uShootMotion();
  			}
  		}
  	}
  	if (vexRT[Btn6D] == 1 || vexRT[Btn6U] == 1) {
  		stopTask(nodebug);
  		stopTask(buttonDebug);
  		stopTask(sensorDebug);
  		stopTask(otherDebug);
  		stopTask(debug2);
  		if (SensorValue[motion] > 1) {
  			startTask(debug);
  			uShoot();
  		}
  		else if (SensorValue[motion] == 0) {
  			startTask(debugMotion);
  			uShootMotion();
  		}
  	}
  	else if (vexRT[Btn7U] == 1 && TIMER >= 100) {
  		stopTask(nodebug);
  		stopTask(buttonDebug);
  		stopTask(sensorDebug);
  		stopTask(otherDebug);
  		stopTask(debug);
  		stopTask(debugMotion);
  		startTask(debug2);
  	}
  	else if (vexRT[Btn8U] == 1 || nLCDButtons == 1){
  		stopTask(debug);
  		stopTask(buttonDebug);
  		stopTask(sensorDebug);
  		stopTask(otherDebug);
  		stopTask(debug2);
  		stopTask(debugMotion);
  		startTask(nodebug);
  	}
  	else if (vexRT[Btn8R] == 1 || nLCDButtons == 2) {
  		stopTask(debug);
  		stopTask(nodebug);
  		stopTask(sensorDebug);
  		stopTask(otherDebug);
  		stopTask(debug2);
  		stopTask(debugMotion);
  		startTask(buttonDebug);
  	}
  	else if (vexRT[Btn8D] == 1 || nLCDButtons == 4) {
  		stopTask(debug);
  		stopTask(nodebug);
  		stopTask(otherDebug);
  		stopTask(buttonDebug);
  		stopTask(debug2);
  		stopTask(debugMotion);
  		startTask(sensorDebug);
  	}
  	else if (vexRT[Btn8L] == 1 || nLCDButtons == 3) {
  		stopTask(debug);
  		stopTask(nodebug);
  		stopTask(buttonDebug);
  		stopTask(sensorDebug);
  		stopTask(debug2);
  		stopTask(debugMotion);
  		startTask(otherDebug);
  	}
	}
}
